// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auth.proto

package authpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/mwitkow/go-proto-validators"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type JWTPurpose int32

const (
	JWTPurpose_AUTHENTICATION   JWTPurpose = 0
	JWTPurpose_RESOURCES_ACCESS JWTPurpose = 1
	JWTPurpose_VALIDATION       JWTPurpose = 2
)

var JWTPurpose_name = map[int32]string{
	0: "AUTHENTICATION",
	1: "RESOURCES_ACCESS",
	2: "VALIDATION",
}

var JWTPurpose_value = map[string]int32{
	"AUTHENTICATION":   0,
	"RESOURCES_ACCESS": 1,
	"VALIDATION":       2,
}

func (x JWTPurpose) String() string {
	return proto.EnumName(JWTPurpose_name, int32(x))
}

func (JWTPurpose) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{0}
}

type JWTState int32

const (
	JWTState_VALID         JWTState = 0
	JWTState_NOT_VALID     JWTState = 1
	JWTState_EXPIRED       JWTState = 2
	JWTState_REVOKED       JWTState = 3
	JWTState_NOT_SIGNED    JWTState = 4
	JWTState_NOT_EFFECTIVE JWTState = 5
)

var JWTState_name = map[int32]string{
	0: "VALID",
	1: "NOT_VALID",
	2: "EXPIRED",
	3: "REVOKED",
	4: "NOT_SIGNED",
	5: "NOT_EFFECTIVE",
}

var JWTState_value = map[string]int32{
	"VALID":         0,
	"NOT_VALID":     1,
	"EXPIRED":       2,
	"REVOKED":       3,
	"NOT_SIGNED":    4,
	"NOT_EFFECTIVE": 5,
}

func (x JWTState) String() string {
	return proto.EnumName(JWTState_name, int32(x))
}

func (JWTState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{1}
}

type EventAction int32

const (
	EventAction_Delete EventAction = 0
	EventAction_Save   EventAction = 1
)

var EventAction_name = map[int32]string{
	0: "Delete",
	1: "Save",
}

var EventAction_value = map[string]int32{
	"Delete": 0,
	"Save":   1,
}

func (x EventAction) String() string {
	return proto.EnumName(EventAction_name, int32(x))
}

func (EventAction) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{2}
}

type JWTHeader struct {
	Typ                  string   `protobuf:"bytes,1,opt,name=typ,proto3" json:"typ,omitempty"`
	Alg                  string   `protobuf:"bytes,2,opt,name=alg,proto3" json:"alg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JWTHeader) Reset()         { *m = JWTHeader{} }
func (m *JWTHeader) String() string { return proto.CompactTextString(m) }
func (*JWTHeader) ProtoMessage()    {}
func (*JWTHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{0}
}

func (m *JWTHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JWTHeader.Unmarshal(m, b)
}
func (m *JWTHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JWTHeader.Marshal(b, m, deterministic)
}
func (m *JWTHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JWTHeader.Merge(m, src)
}
func (m *JWTHeader) XXX_Size() int {
	return xxx_messageInfo_JWTHeader.Size(m)
}
func (m *JWTHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_JWTHeader.DiscardUnknown(m)
}

var xxx_messageInfo_JWTHeader proto.InternalMessageInfo

func (m *JWTHeader) GetTyp() string {
	if m != nil {
		return m.Typ
	}
	return ""
}

func (m *JWTHeader) GetAlg() string {
	if m != nil {
		return m.Alg
	}
	return ""
}

type Profile struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	FamilyName           string   `protobuf:"bytes,2,opt,name=family_name,json=familyName,proto3" json:"family_name,omitempty"`
	GivenName            string   `protobuf:"bytes,3,opt,name=given_name,json=givenName,proto3" json:"given_name,omitempty"`
	MiddleName           string   `protobuf:"bytes,4,opt,name=middle_name,json=middleName,proto3" json:"middle_name,omitempty"`
	Nickname             string   `protobuf:"bytes,5,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Picture              string   `protobuf:"bytes,6,opt,name=picture,proto3" json:"picture,omitempty"`
	UpdatedAt            int64    `protobuf:"varint,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Profile) Reset()         { *m = Profile{} }
func (m *Profile) String() string { return proto.CompactTextString(m) }
func (*Profile) ProtoMessage()    {}
func (*Profile) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{1}
}

func (m *Profile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Profile.Unmarshal(m, b)
}
func (m *Profile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Profile.Marshal(b, m, deterministic)
}
func (m *Profile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Profile.Merge(m, src)
}
func (m *Profile) XXX_Size() int {
	return xxx_messageInfo_Profile.Size(m)
}
func (m *Profile) XXX_DiscardUnknown() {
	xxx_messageInfo_Profile.DiscardUnknown(m)
}

var xxx_messageInfo_Profile proto.InternalMessageInfo

func (m *Profile) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Profile) GetFamilyName() string {
	if m != nil {
		return m.FamilyName
	}
	return ""
}

func (m *Profile) GetGivenName() string {
	if m != nil {
		return m.GivenName
	}
	return ""
}

func (m *Profile) GetMiddleName() string {
	if m != nil {
		return m.MiddleName
	}
	return ""
}

func (m *Profile) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *Profile) GetPicture() string {
	if m != nil {
		return m.Picture
	}
	return ""
}

func (m *Profile) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

type Email struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	EmailVerified        bool     `protobuf:"varint,2,opt,name=email_verified,json=emailVerified,proto3" json:"email_verified,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Email) Reset()         { *m = Email{} }
func (m *Email) String() string { return proto.CompactTextString(m) }
func (*Email) ProtoMessage()    {}
func (*Email) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{2}
}

func (m *Email) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Email.Unmarshal(m, b)
}
func (m *Email) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Email.Marshal(b, m, deterministic)
}
func (m *Email) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Email.Merge(m, src)
}
func (m *Email) XXX_Size() int {
	return xxx_messageInfo_Email.Size(m)
}
func (m *Email) XXX_DiscardUnknown() {
	xxx_messageInfo_Email.DiscardUnknown(m)
}

var xxx_messageInfo_Email proto.InternalMessageInfo

func (m *Email) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Email) GetEmailVerified() bool {
	if m != nil {
		return m.EmailVerified
	}
	return false
}

type Claims struct {
	Iss                  string   `protobuf:"bytes,1,opt,name=iss,proto3" json:"iss,omitempty"`
	Sub                  string   `protobuf:"bytes,2,opt,name=sub,proto3" json:"sub,omitempty"`
	Aud                  string   `protobuf:"bytes,3,opt,name=aud,proto3" json:"aud,omitempty"`
	Exp                  int64    `protobuf:"varint,4,opt,name=exp,proto3" json:"exp,omitempty"`
	Nbf                  int64    `protobuf:"varint,5,opt,name=nbf,proto3" json:"nbf,omitempty"`
	Iat                  int64    `protobuf:"varint,6,opt,name=iat,proto3" json:"iat,omitempty"`
	Jti                  string   `protobuf:"bytes,7,opt,name=jti,proto3" json:"jti,omitempty"`
	Name                 string   `protobuf:"bytes,8,opt,name=name,proto3" json:"name,omitempty"`
	Picture              string   `protobuf:"bytes,9,opt,name=picture,proto3" json:"picture,omitempty"`
	Email                string   `protobuf:"bytes,10,opt,name=email,proto3" json:"email,omitempty"`
	EmailVerified        bool     `protobuf:"varint,11,opt,name=email_verified,json=emailVerified,proto3" json:"email_verified,omitempty"`
	ApiAccess            []string `protobuf:"bytes,12,rep,name=api_access,json=apiAccess,proto3" json:"api_access,omitempty"`
	JwtStore             string   `protobuf:"bytes,13,opt,name=jwt_store,json=jwtStore,proto3" json:"jwt_store,omitempty"`
	JwkCert              string   `protobuf:"bytes,14,opt,name=jwk_cert,json=jwkCert,proto3" json:"jwk_cert,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Claims) Reset()         { *m = Claims{} }
func (m *Claims) String() string { return proto.CompactTextString(m) }
func (*Claims) ProtoMessage()    {}
func (*Claims) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{3}
}

func (m *Claims) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Claims.Unmarshal(m, b)
}
func (m *Claims) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Claims.Marshal(b, m, deterministic)
}
func (m *Claims) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Claims.Merge(m, src)
}
func (m *Claims) XXX_Size() int {
	return xxx_messageInfo_Claims.Size(m)
}
func (m *Claims) XXX_DiscardUnknown() {
	xxx_messageInfo_Claims.DiscardUnknown(m)
}

var xxx_messageInfo_Claims proto.InternalMessageInfo

func (m *Claims) GetIss() string {
	if m != nil {
		return m.Iss
	}
	return ""
}

func (m *Claims) GetSub() string {
	if m != nil {
		return m.Sub
	}
	return ""
}

func (m *Claims) GetAud() string {
	if m != nil {
		return m.Aud
	}
	return ""
}

func (m *Claims) GetExp() int64 {
	if m != nil {
		return m.Exp
	}
	return 0
}

func (m *Claims) GetNbf() int64 {
	if m != nil {
		return m.Nbf
	}
	return 0
}

func (m *Claims) GetIat() int64 {
	if m != nil {
		return m.Iat
	}
	return 0
}

func (m *Claims) GetJti() string {
	if m != nil {
		return m.Jti
	}
	return ""
}

func (m *Claims) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Claims) GetPicture() string {
	if m != nil {
		return m.Picture
	}
	return ""
}

func (m *Claims) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Claims) GetEmailVerified() bool {
	if m != nil {
		return m.EmailVerified
	}
	return false
}

func (m *Claims) GetApiAccess() []string {
	if m != nil {
		return m.ApiAccess
	}
	return nil
}

func (m *Claims) GetJwtStore() string {
	if m != nil {
		return m.JwtStore
	}
	return ""
}

func (m *Claims) GetJwkCert() string {
	if m != nil {
		return m.JwkCert
	}
	return ""
}

type JWT struct {
	Header               *JWTHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Claims               *Claims    `protobuf:"bytes,2,opt,name=claims,proto3" json:"claims,omitempty"`
	Signature            string     `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *JWT) Reset()         { *m = JWT{} }
func (m *JWT) String() string { return proto.CompactTextString(m) }
func (*JWT) ProtoMessage()    {}
func (*JWT) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{4}
}

func (m *JWT) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JWT.Unmarshal(m, b)
}
func (m *JWT) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JWT.Marshal(b, m, deterministic)
}
func (m *JWT) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JWT.Merge(m, src)
}
func (m *JWT) XXX_Size() int {
	return xxx_messageInfo_JWT.Size(m)
}
func (m *JWT) XXX_DiscardUnknown() {
	xxx_messageInfo_JWT.DiscardUnknown(m)
}

var xxx_messageInfo_JWT proto.InternalMessageInfo

func (m *JWT) GetHeader() *JWTHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *JWT) GetClaims() *Claims {
	if m != nil {
		return m.Claims
	}
	return nil
}

func (m *JWT) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

type Credentials struct {
	Subject              string   `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Credentials) Reset()         { *m = Credentials{} }
func (m *Credentials) String() string { return proto.CompactTextString(m) }
func (*Credentials) ProtoMessage()    {}
func (*Credentials) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{5}
}

func (m *Credentials) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Credentials.Unmarshal(m, b)
}
func (m *Credentials) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Credentials.Marshal(b, m, deterministic)
}
func (m *Credentials) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Credentials.Merge(m, src)
}
func (m *Credentials) XXX_Size() int {
	return xxx_messageInfo_Credentials.Size(m)
}
func (m *Credentials) XXX_DiscardUnknown() {
	xxx_messageInfo_Credentials.DiscardUnknown(m)
}

var xxx_messageInfo_Credentials proto.InternalMessageInfo

func (m *Credentials) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *Credentials) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Credentials) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type SyncMessage struct {
	Action               EventAction `protobuf:"varint,1,opt,name=action,proto3,enum=authpb.EventAction" json:"action,omitempty"`
	Jti                  string      `protobuf:"bytes,2,opt,name=jti,proto3" json:"jti,omitempty"`
	Info                 *JwtInfo    `protobuf:"bytes,3,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *SyncMessage) Reset()         { *m = SyncMessage{} }
func (m *SyncMessage) String() string { return proto.CompactTextString(m) }
func (*SyncMessage) ProtoMessage()    {}
func (*SyncMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{6}
}

func (m *SyncMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncMessage.Unmarshal(m, b)
}
func (m *SyncMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncMessage.Marshal(b, m, deterministic)
}
func (m *SyncMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncMessage.Merge(m, src)
}
func (m *SyncMessage) XXX_Size() int {
	return xxx_messageInfo_SyncMessage.Size(m)
}
func (m *SyncMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncMessage.DiscardUnknown(m)
}

var xxx_messageInfo_SyncMessage proto.InternalMessageInfo

func (m *SyncMessage) GetAction() EventAction {
	if m != nil {
		return m.Action
	}
	return EventAction_Delete
}

func (m *SyncMessage) GetJti() string {
	if m != nil {
		return m.Jti
	}
	return ""
}

func (m *SyncMessage) GetInfo() *JwtInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

type JwtInfo struct {
	Jti                  string   `protobuf:"bytes,1,opt,name=jti,proto3" json:"jti,omitempty"`
	Nbf                  int64    `protobuf:"varint,2,opt,name=nbf,proto3" json:"nbf,omitempty"`
	Exp                  int64    `protobuf:"varint,3,opt,name=exp,proto3" json:"exp,omitempty"`
	State                JWTState `protobuf:"varint,4,opt,name=state,proto3,enum=authpb.JWTState" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JwtInfo) Reset()         { *m = JwtInfo{} }
func (m *JwtInfo) String() string { return proto.CompactTextString(m) }
func (*JwtInfo) ProtoMessage()    {}
func (*JwtInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{7}
}

func (m *JwtInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JwtInfo.Unmarshal(m, b)
}
func (m *JwtInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JwtInfo.Marshal(b, m, deterministic)
}
func (m *JwtInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JwtInfo.Merge(m, src)
}
func (m *JwtInfo) XXX_Size() int {
	return xxx_messageInfo_JwtInfo.Size(m)
}
func (m *JwtInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_JwtInfo.DiscardUnknown(m)
}

var xxx_messageInfo_JwtInfo proto.InternalMessageInfo

func (m *JwtInfo) GetJti() string {
	if m != nil {
		return m.Jti
	}
	return ""
}

func (m *JwtInfo) GetNbf() int64 {
	if m != nil {
		return m.Nbf
	}
	return 0
}

func (m *JwtInfo) GetExp() int64 {
	if m != nil {
		return m.Exp
	}
	return 0
}

func (m *JwtInfo) GetState() JWTState {
	if m != nil {
		return m.State
	}
	return JWTState_VALID
}

type JwtEvent struct {
	Action               EventAction `protobuf:"varint,1,opt,name=action,proto3,enum=authpb.EventAction" json:"action,omitempty"`
	Info                 *JwtInfo    `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *JwtEvent) Reset()         { *m = JwtEvent{} }
func (m *JwtEvent) String() string { return proto.CompactTextString(m) }
func (*JwtEvent) ProtoMessage()    {}
func (*JwtEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{8}
}

func (m *JwtEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JwtEvent.Unmarshal(m, b)
}
func (m *JwtEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JwtEvent.Marshal(b, m, deterministic)
}
func (m *JwtEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JwtEvent.Merge(m, src)
}
func (m *JwtEvent) XXX_Size() int {
	return xxx_messageInfo_JwtEvent.Size(m)
}
func (m *JwtEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_JwtEvent.DiscardUnknown(m)
}

var xxx_messageInfo_JwtEvent proto.InternalMessageInfo

func (m *JwtEvent) GetAction() EventAction {
	if m != nil {
		return m.Action
	}
	return EventAction_Delete
}

func (m *JwtEvent) GetInfo() *JwtInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

type FeedResponse struct {
	Error                string   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Jti                  string   `protobuf:"bytes,2,opt,name=jti,proto3" json:"jti,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FeedResponse) Reset()         { *m = FeedResponse{} }
func (m *FeedResponse) String() string { return proto.CompactTextString(m) }
func (*FeedResponse) ProtoMessage()    {}
func (*FeedResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{9}
}

func (m *FeedResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FeedResponse.Unmarshal(m, b)
}
func (m *FeedResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FeedResponse.Marshal(b, m, deterministic)
}
func (m *FeedResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeedResponse.Merge(m, src)
}
func (m *FeedResponse) XXX_Size() int {
	return xxx_messageInfo_FeedResponse.Size(m)
}
func (m *FeedResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FeedResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FeedResponse proto.InternalMessageInfo

func (m *FeedResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *FeedResponse) GetJti() string {
	if m != nil {
		return m.Jti
	}
	return ""
}

type FindJWTRequest struct {
	Jti                  string   `protobuf:"bytes,1,opt,name=jti,proto3" json:"jti,omitempty"`
	Signature            string   `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindJWTRequest) Reset()         { *m = FindJWTRequest{} }
func (m *FindJWTRequest) String() string { return proto.CompactTextString(m) }
func (*FindJWTRequest) ProtoMessage()    {}
func (*FindJWTRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{10}
}

func (m *FindJWTRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindJWTRequest.Unmarshal(m, b)
}
func (m *FindJWTRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindJWTRequest.Marshal(b, m, deterministic)
}
func (m *FindJWTRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindJWTRequest.Merge(m, src)
}
func (m *FindJWTRequest) XXX_Size() int {
	return xxx_messageInfo_FindJWTRequest.Size(m)
}
func (m *FindJWTRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindJWTRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindJWTRequest proto.InternalMessageInfo

func (m *FindJWTRequest) GetJti() string {
	if m != nil {
		return m.Jti
	}
	return ""
}

func (m *FindJWTRequest) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

type FindJWTResponse struct {
	State                JWTState `protobuf:"varint,1,opt,name=state,proto3,enum=authpb.JWTState" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindJWTResponse) Reset()         { *m = FindJWTResponse{} }
func (m *FindJWTResponse) String() string { return proto.CompactTextString(m) }
func (*FindJWTResponse) ProtoMessage()    {}
func (*FindJWTResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{11}
}

func (m *FindJWTResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindJWTResponse.Unmarshal(m, b)
}
func (m *FindJWTResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindJWTResponse.Marshal(b, m, deterministic)
}
func (m *FindJWTResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindJWTResponse.Merge(m, src)
}
func (m *FindJWTResponse) XXX_Size() int {
	return xxx_messageInfo_FindJWTResponse.Size(m)
}
func (m *FindJWTResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FindJWTResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FindJWTResponse proto.InternalMessageInfo

func (m *FindJWTResponse) GetState() JWTState {
	if m != nil {
		return m.State
	}
	return JWTState_VALID
}

type SaveTokenRequest struct {
	Info                 *JwtInfo `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SaveTokenRequest) Reset()         { *m = SaveTokenRequest{} }
func (m *SaveTokenRequest) String() string { return proto.CompactTextString(m) }
func (*SaveTokenRequest) ProtoMessage()    {}
func (*SaveTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{12}
}

func (m *SaveTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveTokenRequest.Unmarshal(m, b)
}
func (m *SaveTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveTokenRequest.Marshal(b, m, deterministic)
}
func (m *SaveTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveTokenRequest.Merge(m, src)
}
func (m *SaveTokenRequest) XXX_Size() int {
	return xxx_messageInfo_SaveTokenRequest.Size(m)
}
func (m *SaveTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SaveTokenRequest proto.InternalMessageInfo

func (m *SaveTokenRequest) GetInfo() *JwtInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

type SaveTokenResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SaveTokenResponse) Reset()         { *m = SaveTokenResponse{} }
func (m *SaveTokenResponse) String() string { return proto.CompactTextString(m) }
func (*SaveTokenResponse) ProtoMessage()    {}
func (*SaveTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{13}
}

func (m *SaveTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveTokenResponse.Unmarshal(m, b)
}
func (m *SaveTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveTokenResponse.Marshal(b, m, deterministic)
}
func (m *SaveTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveTokenResponse.Merge(m, src)
}
func (m *SaveTokenResponse) XXX_Size() int {
	return xxx_messageInfo_SaveTokenResponse.Size(m)
}
func (m *SaveTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SaveTokenResponse proto.InternalMessageInfo

type DeleteJWTRequest struct {
	Jti                  string   `protobuf:"bytes,1,opt,name=jti,proto3" json:"jti,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteJWTRequest) Reset()         { *m = DeleteJWTRequest{} }
func (m *DeleteJWTRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteJWTRequest) ProtoMessage()    {}
func (*DeleteJWTRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{14}
}

func (m *DeleteJWTRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteJWTRequest.Unmarshal(m, b)
}
func (m *DeleteJWTRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteJWTRequest.Marshal(b, m, deterministic)
}
func (m *DeleteJWTRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteJWTRequest.Merge(m, src)
}
func (m *DeleteJWTRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteJWTRequest.Size(m)
}
func (m *DeleteJWTRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteJWTRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteJWTRequest proto.InternalMessageInfo

func (m *DeleteJWTRequest) GetJti() string {
	if m != nil {
		return m.Jti
	}
	return ""
}

type DeleteJWTResponse struct {
	Count                uint32   `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteJWTResponse) Reset()         { *m = DeleteJWTResponse{} }
func (m *DeleteJWTResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteJWTResponse) ProtoMessage()    {}
func (*DeleteJWTResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{15}
}

func (m *DeleteJWTResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteJWTResponse.Unmarshal(m, b)
}
func (m *DeleteJWTResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteJWTResponse.Marshal(b, m, deterministic)
}
func (m *DeleteJWTResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteJWTResponse.Merge(m, src)
}
func (m *DeleteJWTResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteJWTResponse.Size(m)
}
func (m *DeleteJWTResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteJWTResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteJWTResponse proto.InternalMessageInfo

func (m *DeleteJWTResponse) GetCount() uint32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type RevokeTokenRequest struct {
	Jwt                  *JWT     `protobuf:"bytes,1,opt,name=jwt,proto3" json:"jwt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RevokeTokenRequest) Reset()         { *m = RevokeTokenRequest{} }
func (m *RevokeTokenRequest) String() string { return proto.CompactTextString(m) }
func (*RevokeTokenRequest) ProtoMessage()    {}
func (*RevokeTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{16}
}

func (m *RevokeTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RevokeTokenRequest.Unmarshal(m, b)
}
func (m *RevokeTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RevokeTokenRequest.Marshal(b, m, deterministic)
}
func (m *RevokeTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RevokeTokenRequest.Merge(m, src)
}
func (m *RevokeTokenRequest) XXX_Size() int {
	return xxx_messageInfo_RevokeTokenRequest.Size(m)
}
func (m *RevokeTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RevokeTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RevokeTokenRequest proto.InternalMessageInfo

func (m *RevokeTokenRequest) GetJwt() *JWT {
	if m != nil {
		return m.Jwt
	}
	return nil
}

type RevokeTokenResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RevokeTokenResponse) Reset()         { *m = RevokeTokenResponse{} }
func (m *RevokeTokenResponse) String() string { return proto.CompactTextString(m) }
func (*RevokeTokenResponse) ProtoMessage()    {}
func (*RevokeTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{17}
}

func (m *RevokeTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RevokeTokenResponse.Unmarshal(m, b)
}
func (m *RevokeTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RevokeTokenResponse.Marshal(b, m, deterministic)
}
func (m *RevokeTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RevokeTokenResponse.Merge(m, src)
}
func (m *RevokeTokenResponse) XXX_Size() int {
	return xxx_messageInfo_RevokeTokenResponse.Size(m)
}
func (m *RevokeTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RevokeTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RevokeTokenResponse proto.InternalMessageInfo

type ListenRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListenRequest) Reset()         { *m = ListenRequest{} }
func (m *ListenRequest) String() string { return proto.CompactTextString(m) }
func (*ListenRequest) ProtoMessage()    {}
func (*ListenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{18}
}

func (m *ListenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListenRequest.Unmarshal(m, b)
}
func (m *ListenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListenRequest.Marshal(b, m, deterministic)
}
func (m *ListenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListenRequest.Merge(m, src)
}
func (m *ListenRequest) XXX_Size() int {
	return xxx_messageInfo_ListenRequest.Size(m)
}
func (m *ListenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListenRequest proto.InternalMessageInfo

type CreateCredentialsRequest struct {
	Credentials          *Credentials `protobuf:"bytes,1,opt,name=credentials,proto3" json:"credentials,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *CreateCredentialsRequest) Reset()         { *m = CreateCredentialsRequest{} }
func (m *CreateCredentialsRequest) String() string { return proto.CompactTextString(m) }
func (*CreateCredentialsRequest) ProtoMessage()    {}
func (*CreateCredentialsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{19}
}

func (m *CreateCredentialsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCredentialsRequest.Unmarshal(m, b)
}
func (m *CreateCredentialsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCredentialsRequest.Marshal(b, m, deterministic)
}
func (m *CreateCredentialsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCredentialsRequest.Merge(m, src)
}
func (m *CreateCredentialsRequest) XXX_Size() int {
	return xxx_messageInfo_CreateCredentialsRequest.Size(m)
}
func (m *CreateCredentialsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCredentialsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCredentialsRequest proto.InternalMessageInfo

func (m *CreateCredentialsRequest) GetCredentials() *Credentials {
	if m != nil {
		return m.Credentials
	}
	return nil
}

type CreateCredentialsResponse struct {
	UserTaken            bool     `protobuf:"varint,1,opt,name=user_taken,json=userTaken,proto3" json:"user_taken,omitempty"`
	EmailTaken           bool     `protobuf:"varint,2,opt,name=email_taken,json=emailTaken,proto3" json:"email_taken,omitempty"`
	Code                 string   `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateCredentialsResponse) Reset()         { *m = CreateCredentialsResponse{} }
func (m *CreateCredentialsResponse) String() string { return proto.CompactTextString(m) }
func (*CreateCredentialsResponse) ProtoMessage()    {}
func (*CreateCredentialsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{20}
}

func (m *CreateCredentialsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCredentialsResponse.Unmarshal(m, b)
}
func (m *CreateCredentialsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCredentialsResponse.Marshal(b, m, deterministic)
}
func (m *CreateCredentialsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCredentialsResponse.Merge(m, src)
}
func (m *CreateCredentialsResponse) XXX_Size() int {
	return xxx_messageInfo_CreateCredentialsResponse.Size(m)
}
func (m *CreateCredentialsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCredentialsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCredentialsResponse proto.InternalMessageInfo

func (m *CreateCredentialsResponse) GetUserTaken() bool {
	if m != nil {
		return m.UserTaken
	}
	return false
}

func (m *CreateCredentialsResponse) GetEmailTaken() bool {
	if m != nil {
		return m.EmailTaken
	}
	return false
}

func (m *CreateCredentialsResponse) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type UpdateEmailRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	OldEmail             string   `protobuf:"bytes,2,opt,name=old_email,json=oldEmail,proto3" json:"old_email,omitempty"`
	NewEmail             string   `protobuf:"bytes,3,opt,name=new_email,json=newEmail,proto3" json:"new_email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateEmailRequest) Reset()         { *m = UpdateEmailRequest{} }
func (m *UpdateEmailRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateEmailRequest) ProtoMessage()    {}
func (*UpdateEmailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{21}
}

func (m *UpdateEmailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateEmailRequest.Unmarshal(m, b)
}
func (m *UpdateEmailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateEmailRequest.Marshal(b, m, deterministic)
}
func (m *UpdateEmailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateEmailRequest.Merge(m, src)
}
func (m *UpdateEmailRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateEmailRequest.Size(m)
}
func (m *UpdateEmailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateEmailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateEmailRequest proto.InternalMessageInfo

func (m *UpdateEmailRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UpdateEmailRequest) GetOldEmail() string {
	if m != nil {
		return m.OldEmail
	}
	return ""
}

func (m *UpdateEmailRequest) GetNewEmail() string {
	if m != nil {
		return m.NewEmail
	}
	return ""
}

type UpdateEmailResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateEmailResponse) Reset()         { *m = UpdateEmailResponse{} }
func (m *UpdateEmailResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateEmailResponse) ProtoMessage()    {}
func (*UpdateEmailResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{22}
}

func (m *UpdateEmailResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateEmailResponse.Unmarshal(m, b)
}
func (m *UpdateEmailResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateEmailResponse.Marshal(b, m, deterministic)
}
func (m *UpdateEmailResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateEmailResponse.Merge(m, src)
}
func (m *UpdateEmailResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateEmailResponse.Size(m)
}
func (m *UpdateEmailResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateEmailResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateEmailResponse proto.InternalMessageInfo

type AuthenticateRequest struct {
	Subject              string   `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthenticateRequest) Reset()         { *m = AuthenticateRequest{} }
func (m *AuthenticateRequest) String() string { return proto.CompactTextString(m) }
func (*AuthenticateRequest) ProtoMessage()    {}
func (*AuthenticateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{23}
}

func (m *AuthenticateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthenticateRequest.Unmarshal(m, b)
}
func (m *AuthenticateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthenticateRequest.Marshal(b, m, deterministic)
}
func (m *AuthenticateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthenticateRequest.Merge(m, src)
}
func (m *AuthenticateRequest) XXX_Size() int {
	return xxx_messageInfo_AuthenticateRequest.Size(m)
}
func (m *AuthenticateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthenticateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthenticateRequest proto.InternalMessageInfo

func (m *AuthenticateRequest) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *AuthenticateRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type AuthenticateResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthenticateResponse) Reset()         { *m = AuthenticateResponse{} }
func (m *AuthenticateResponse) String() string { return proto.CompactTextString(m) }
func (*AuthenticateResponse) ProtoMessage()    {}
func (*AuthenticateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{24}
}

func (m *AuthenticateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthenticateResponse.Unmarshal(m, b)
}
func (m *AuthenticateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthenticateResponse.Marshal(b, m, deterministic)
}
func (m *AuthenticateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthenticateResponse.Merge(m, src)
}
func (m *AuthenticateResponse) XXX_Size() int {
	return xxx_messageInfo_AuthenticateResponse.Size(m)
}
func (m *AuthenticateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthenticateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AuthenticateResponse proto.InternalMessageInfo

func (m *AuthenticateResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type SetPasswordRequest struct {
	User                 string   `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	OldPassword          string   `protobuf:"bytes,3,opt,name=old_password,json=oldPassword,proto3" json:"old_password,omitempty"`
	NewPassword          string   `protobuf:"bytes,4,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetPasswordRequest) Reset()         { *m = SetPasswordRequest{} }
func (m *SetPasswordRequest) String() string { return proto.CompactTextString(m) }
func (*SetPasswordRequest) ProtoMessage()    {}
func (*SetPasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{25}
}

func (m *SetPasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetPasswordRequest.Unmarshal(m, b)
}
func (m *SetPasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetPasswordRequest.Marshal(b, m, deterministic)
}
func (m *SetPasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetPasswordRequest.Merge(m, src)
}
func (m *SetPasswordRequest) XXX_Size() int {
	return xxx_messageInfo_SetPasswordRequest.Size(m)
}
func (m *SetPasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetPasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetPasswordRequest proto.InternalMessageInfo

func (m *SetPasswordRequest) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *SetPasswordRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *SetPasswordRequest) GetOldPassword() string {
	if m != nil {
		return m.OldPassword
	}
	return ""
}

func (m *SetPasswordRequest) GetNewPassword() string {
	if m != nil {
		return m.NewPassword
	}
	return ""
}

type SetPasswordResponse struct {
	AlreadyUsed          bool     `protobuf:"varint,1,opt,name=already_used,json=alreadyUsed,proto3" json:"already_used,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetPasswordResponse) Reset()         { *m = SetPasswordResponse{} }
func (m *SetPasswordResponse) String() string { return proto.CompactTextString(m) }
func (*SetPasswordResponse) ProtoMessage()    {}
func (*SetPasswordResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{26}
}

func (m *SetPasswordResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetPasswordResponse.Unmarshal(m, b)
}
func (m *SetPasswordResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetPasswordResponse.Marshal(b, m, deterministic)
}
func (m *SetPasswordResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetPasswordResponse.Merge(m, src)
}
func (m *SetPasswordResponse) XXX_Size() int {
	return xxx_messageInfo_SetPasswordResponse.Size(m)
}
func (m *SetPasswordResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetPasswordResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetPasswordResponse proto.InternalMessageInfo

func (m *SetPasswordResponse) GetAlreadyUsed() bool {
	if m != nil {
		return m.AlreadyUsed
	}
	return false
}

type CreateTokenRequest struct {
	Sub                  string            `protobuf:"bytes,1,opt,name=sub,proto3" json:"sub,omitempty"`
	Audience             string            `protobuf:"bytes,2,opt,name=audience,proto3" json:"audience,omitempty"`
	Scope                []string          `protobuf:"bytes,3,rep,name=scope,proto3" json:"scope,omitempty"`
	ScopeValues          map[string]string `protobuf:"bytes,4,rep,name=scope_values,json=scopeValues,proto3" json:"scope_values,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Data                 map[string]string `protobuf:"bytes,5,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *CreateTokenRequest) Reset()         { *m = CreateTokenRequest{} }
func (m *CreateTokenRequest) String() string { return proto.CompactTextString(m) }
func (*CreateTokenRequest) ProtoMessage()    {}
func (*CreateTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{27}
}

func (m *CreateTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTokenRequest.Unmarshal(m, b)
}
func (m *CreateTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTokenRequest.Marshal(b, m, deterministic)
}
func (m *CreateTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTokenRequest.Merge(m, src)
}
func (m *CreateTokenRequest) XXX_Size() int {
	return xxx_messageInfo_CreateTokenRequest.Size(m)
}
func (m *CreateTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTokenRequest proto.InternalMessageInfo

func (m *CreateTokenRequest) GetSub() string {
	if m != nil {
		return m.Sub
	}
	return ""
}

func (m *CreateTokenRequest) GetAudience() string {
	if m != nil {
		return m.Audience
	}
	return ""
}

func (m *CreateTokenRequest) GetScope() []string {
	if m != nil {
		return m.Scope
	}
	return nil
}

func (m *CreateTokenRequest) GetScopeValues() map[string]string {
	if m != nil {
		return m.ScopeValues
	}
	return nil
}

func (m *CreateTokenRequest) GetData() map[string]string {
	if m != nil {
		return m.Data
	}
	return nil
}

type CreateTokenResponse struct {
	Jwt                  *JWT     `protobuf:"bytes,1,opt,name=jwt,proto3" json:"jwt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateTokenResponse) Reset()         { *m = CreateTokenResponse{} }
func (m *CreateTokenResponse) String() string { return proto.CompactTextString(m) }
func (*CreateTokenResponse) ProtoMessage()    {}
func (*CreateTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{28}
}

func (m *CreateTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTokenResponse.Unmarshal(m, b)
}
func (m *CreateTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTokenResponse.Marshal(b, m, deterministic)
}
func (m *CreateTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTokenResponse.Merge(m, src)
}
func (m *CreateTokenResponse) XXX_Size() int {
	return xxx_messageInfo_CreateTokenResponse.Size(m)
}
func (m *CreateTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTokenResponse proto.InternalMessageInfo

func (m *CreateTokenResponse) GetJwt() *JWT {
	if m != nil {
		return m.Jwt
	}
	return nil
}

func init() {
	proto.RegisterEnum("authpb.JWTPurpose", JWTPurpose_name, JWTPurpose_value)
	proto.RegisterEnum("authpb.JWTState", JWTState_name, JWTState_value)
	proto.RegisterEnum("authpb.EventAction", EventAction_name, EventAction_value)
	proto.RegisterType((*JWTHeader)(nil), "authpb.JWTHeader")
	proto.RegisterType((*Profile)(nil), "authpb.Profile")
	proto.RegisterType((*Email)(nil), "authpb.Email")
	proto.RegisterType((*Claims)(nil), "authpb.Claims")
	proto.RegisterType((*JWT)(nil), "authpb.JWT")
	proto.RegisterType((*Credentials)(nil), "authpb.Credentials")
	proto.RegisterType((*SyncMessage)(nil), "authpb.SyncMessage")
	proto.RegisterType((*JwtInfo)(nil), "authpb.JwtInfo")
	proto.RegisterType((*JwtEvent)(nil), "authpb.JwtEvent")
	proto.RegisterType((*FeedResponse)(nil), "authpb.FeedResponse")
	proto.RegisterType((*FindJWTRequest)(nil), "authpb.FindJWTRequest")
	proto.RegisterType((*FindJWTResponse)(nil), "authpb.FindJWTResponse")
	proto.RegisterType((*SaveTokenRequest)(nil), "authpb.SaveTokenRequest")
	proto.RegisterType((*SaveTokenResponse)(nil), "authpb.SaveTokenResponse")
	proto.RegisterType((*DeleteJWTRequest)(nil), "authpb.DeleteJWTRequest")
	proto.RegisterType((*DeleteJWTResponse)(nil), "authpb.DeleteJWTResponse")
	proto.RegisterType((*RevokeTokenRequest)(nil), "authpb.RevokeTokenRequest")
	proto.RegisterType((*RevokeTokenResponse)(nil), "authpb.RevokeTokenResponse")
	proto.RegisterType((*ListenRequest)(nil), "authpb.ListenRequest")
	proto.RegisterType((*CreateCredentialsRequest)(nil), "authpb.CreateCredentialsRequest")
	proto.RegisterType((*CreateCredentialsResponse)(nil), "authpb.CreateCredentialsResponse")
	proto.RegisterType((*UpdateEmailRequest)(nil), "authpb.UpdateEmailRequest")
	proto.RegisterType((*UpdateEmailResponse)(nil), "authpb.UpdateEmailResponse")
	proto.RegisterType((*AuthenticateRequest)(nil), "authpb.AuthenticateRequest")
	proto.RegisterType((*AuthenticateResponse)(nil), "authpb.AuthenticateResponse")
	proto.RegisterType((*SetPasswordRequest)(nil), "authpb.SetPasswordRequest")
	proto.RegisterType((*SetPasswordResponse)(nil), "authpb.SetPasswordResponse")
	proto.RegisterType((*CreateTokenRequest)(nil), "authpb.CreateTokenRequest")
	proto.RegisterMapType((map[string]string)(nil), "authpb.CreateTokenRequest.DataEntry")
	proto.RegisterMapType((map[string]string)(nil), "authpb.CreateTokenRequest.ScopeValuesEntry")
	proto.RegisterType((*CreateTokenResponse)(nil), "authpb.CreateTokenResponse")
}

func init() { proto.RegisterFile("auth.proto", fileDescriptor_8bbd6f3875b0e874) }

var fileDescriptor_8bbd6f3875b0e874 = []byte{
	// 1565 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x57, 0x5d, 0x6f, 0x13, 0x47,
	0x17, 0xce, 0xda, 0x8e, 0x63, 0x1f, 0x27, 0x66, 0x33, 0x81, 0xf7, 0x35, 0x26, 0xbc, 0x84, 0x25,
	0x2f, 0x0a, 0x20, 0x62, 0x64, 0x10, 0xd0, 0x4a, 0xad, 0x30, 0x8e, 0x53, 0x9c, 0xd2, 0x24, 0x5a,
	0x3b, 0x09, 0x48, 0x95, 0xac, 0xc9, 0xee, 0xc4, 0x59, 0x7b, 0xbd, 0x6b, 0x76, 0xc6, 0x76, 0xa3,
	0xaa, 0x37, 0xbd, 0xef, 0x55, 0x7f, 0x46, 0xfb, 0x43, 0x7a, 0xd1, 0x3b, 0x7e, 0x00, 0x12, 0xea,
	0x0f, 0xa9, 0xe6, 0x63, 0xd7, 0xeb, 0x0f, 0x59, 0xe2, 0x6e, 0xce, 0xc7, 0x9c, 0x39, 0xe7, 0x99,
	0x33, 0xcf, 0xd9, 0x05, 0xc0, 0x03, 0x76, 0xb9, 0xdb, 0x0f, 0x7c, 0xe6, 0xa3, 0x34, 0x5f, 0xf7,
	0xcf, 0x8b, 0x9b, 0x6d, 0xdf, 0x6f, 0xbb, 0xa4, 0x84, 0xfb, 0x4e, 0x09, 0x7b, 0x9e, 0xcf, 0x30,
	0x73, 0x7c, 0x8f, 0x4a, 0xaf, 0xe2, 0xf3, 0xb6, 0xc3, 0x2e, 0x07, 0xe7, 0xbb, 0x96, 0xdf, 0x2b,
	0xf5, 0x46, 0x0e, 0xeb, 0xfa, 0xa3, 0x52, 0xdb, 0x7f, 0x2c, 0x8c, 0x8f, 0x87, 0xd8, 0x75, 0x6c,
	0xcc, 0xfc, 0x80, 0x96, 0xa2, 0xa5, 0xdc, 0x67, 0x94, 0x20, 0x7b, 0x70, 0xd6, 0x7c, 0x43, 0xb0,
	0x4d, 0x02, 0xa4, 0x43, 0x92, 0x5d, 0xf5, 0x0b, 0xda, 0x96, 0xb6, 0x93, 0x35, 0xf9, 0x92, 0x6b,
	0xb0, 0xdb, 0x2e, 0x24, 0xa4, 0x06, 0xbb, 0x6d, 0xe3, 0xa3, 0x06, 0x2b, 0xc7, 0x81, 0x7f, 0xe1,
	0xb8, 0x04, 0x21, 0x48, 0x79, 0xb8, 0x47, 0xd4, 0x06, 0xb1, 0x46, 0x77, 0x20, 0x77, 0x81, 0x7b,
	0x8e, 0x7b, 0xd5, 0x12, 0x26, 0xb9, 0x13, 0xa4, 0xea, 0x90, 0x3b, 0xdc, 0x06, 0x68, 0x3b, 0x43,
	0xe2, 0x49, 0x7b, 0x52, 0xd8, 0xb3, 0x42, 0x73, 0xa8, 0xf6, 0xf7, 0x1c, 0xdb, 0x76, 0x89, 0xb4,
	0xa7, 0xe4, 0x7e, 0xa9, 0x12, 0x0e, 0x45, 0xc8, 0x78, 0x8e, 0xd5, 0x15, 0xd6, 0x65, 0x61, 0x8d,
	0x64, 0x54, 0x80, 0x95, 0xbe, 0x63, 0xb1, 0x41, 0x40, 0x0a, 0x69, 0x61, 0x0a, 0x45, 0x7e, 0xea,
	0xa0, 0x6f, 0x63, 0x46, 0xec, 0x16, 0x66, 0x85, 0x95, 0x2d, 0x6d, 0x27, 0x69, 0x66, 0x95, 0xa6,
	0xc2, 0x8c, 0x3d, 0x58, 0xae, 0xf5, 0xb0, 0xe3, 0xa2, 0xeb, 0xb0, 0x4c, 0xf8, 0x42, 0xd5, 0x24,
	0x05, 0xf4, 0x7f, 0xc8, 0x8b, 0x45, 0x6b, 0x48, 0x02, 0xe7, 0xc2, 0x21, 0xb6, 0xa8, 0x2b, 0x63,
	0xae, 0x09, 0xed, 0xa9, 0x52, 0x1a, 0x7f, 0x25, 0x20, 0x5d, 0x75, 0xb1, 0xd3, 0xa3, 0x1c, 0x38,
	0x87, 0xd2, 0x10, 0x4a, 0x87, 0x0a, 0x0d, 0x1d, 0x9c, 0x87, 0x50, 0xd2, 0xc1, 0xb9, 0x00, 0x77,
	0x60, 0x2b, 0x08, 0xf8, 0x92, 0x6b, 0xc8, 0x4f, 0x7d, 0x51, 0x74, 0xd2, 0xe4, 0x4b, 0xae, 0xf1,
	0xce, 0x2f, 0x44, 0xa1, 0x49, 0x93, 0x2f, 0x45, 0x64, 0xcc, 0x44, 0x7d, 0x49, 0x93, 0x2f, 0xb9,
	0xa6, 0xc3, 0x1c, 0x51, 0x54, 0xd6, 0xe4, 0xcb, 0xe8, 0x62, 0x32, 0xb1, 0x8b, 0x89, 0x61, 0x93,
	0x9d, 0xc4, 0x26, 0xaa, 0x19, 0x16, 0xd7, 0x9c, 0x9b, 0x53, 0x33, 0x07, 0x16, 0xf7, 0x9d, 0x16,
	0xb6, 0x2c, 0x42, 0x69, 0x61, 0x75, 0x2b, 0xc9, 0xaf, 0x13, 0xf7, 0x9d, 0x8a, 0x50, 0xa0, 0x5b,
	0x90, 0xed, 0x8c, 0x58, 0x8b, 0x32, 0x3f, 0x20, 0x85, 0x35, 0x79, 0x5d, 0x9d, 0x11, 0x6b, 0x70,
	0x19, 0xdd, 0x84, 0x4c, 0x67, 0xd4, 0x6d, 0x59, 0x24, 0x60, 0x85, 0xbc, 0xcc, 0xa9, 0x33, 0xea,
	0x56, 0x49, 0xc0, 0x8c, 0x21, 0x24, 0x0f, 0xce, 0x9a, 0xe8, 0x01, 0xa4, 0x2f, 0x45, 0x6f, 0x0a,
	0x24, 0x73, 0xe5, 0xf5, 0x5d, 0xf9, 0x1a, 0x76, 0xa3, 0xa6, 0x35, 0x95, 0x03, 0xba, 0x0f, 0x69,
	0x4b, 0x60, 0x2f, 0x20, 0xce, 0x95, 0xf3, 0xa1, 0xab, 0xbc, 0x11, 0x53, 0x59, 0xd1, 0x26, 0x64,
	0xa9, 0xd3, 0xf6, 0xb0, 0x40, 0x42, 0xb5, 0x5f, 0xa4, 0x30, 0xde, 0x43, 0xae, 0x1a, 0x10, 0x9b,
	0x78, 0xcc, 0xc1, 0x2e, 0xe5, 0xa0, 0xd1, 0xc1, 0x79, 0x87, 0x58, 0x4c, 0x5d, 0x65, 0x28, 0x8e,
	0x41, 0x4b, 0xc4, 0x41, 0x2b, 0x42, 0xa6, 0x8f, 0x29, 0x1d, 0xf9, 0x41, 0x78, 0xaf, 0x91, 0x6c,
	0x7c, 0x80, 0x5c, 0xe3, 0xca, 0xb3, 0x7e, 0x20, 0x94, 0xe2, 0x36, 0x41, 0x8f, 0x20, 0x8d, 0x2d,
	0xfe, 0x84, 0x45, 0xe4, 0x7c, 0x79, 0x23, 0xcc, 0xb7, 0x36, 0x24, 0x1e, 0xab, 0x08, 0x93, 0xa9,
	0x5c, 0xc2, 0x2b, 0x4e, 0x8c, 0xaf, 0xf8, 0x1e, 0xa4, 0x1c, 0xef, 0xc2, 0x17, 0xa7, 0xe4, 0xca,
	0xd7, 0x22, 0x5c, 0x46, 0xac, 0xee, 0x5d, 0xf8, 0xa6, 0x30, 0x1a, 0x6d, 0x58, 0x51, 0x8a, 0x30,
	0x82, 0x36, 0x8e, 0xa0, 0x5a, 0x2b, 0x31, 0xd1, 0x5a, 0xbc, 0xfd, 0x92, 0xe3, 0xf6, 0xbb, 0x0f,
	0xcb, 0x94, 0x61, 0x26, 0xdf, 0x61, 0xbe, 0xac, 0xc7, 0xe0, 0x6f, 0x70, 0xbd, 0x29, 0xcd, 0xc6,
	0x8f, 0x90, 0x39, 0x18, 0x31, 0x91, 0xf9, 0x97, 0x15, 0x16, 0x96, 0x91, 0x58, 0x54, 0xc6, 0x73,
	0x58, 0xdd, 0x27, 0xc4, 0x36, 0x09, 0xed, 0xfb, 0x1e, 0x95, 0x0d, 0x1b, 0x04, 0x7e, 0x10, 0x3d,
	0x52, 0x2e, 0xcc, 0x62, 0x64, 0xbc, 0x82, 0xfc, 0xbe, 0xe3, 0xd9, 0x07, 0x67, 0x4d, 0x93, 0x7c,
	0x18, 0x10, 0xca, 0xe6, 0xa0, 0x30, 0xd1, 0x0e, 0x89, 0xe9, 0x76, 0xf8, 0x0a, 0xae, 0x45, 0x11,
	0xd4, 0xe1, 0x11, 0x24, 0xda, 0x62, 0x48, 0x5e, 0x80, 0xde, 0xc0, 0x43, 0xd2, 0xf4, 0xbb, 0xc4,
	0x0b, 0x8f, 0x0f, 0xab, 0xd5, 0x16, 0x55, 0xbb, 0x01, 0xeb, 0xb1, 0x8d, 0xf2, 0x54, 0x63, 0x1b,
	0xf4, 0x3d, 0xe2, 0x12, 0x46, 0x16, 0x15, 0x63, 0x3c, 0x80, 0xf5, 0x98, 0xd7, 0x18, 0x2d, 0xcb,
	0x1f, 0x78, 0xb2, 0x83, 0xd7, 0x4c, 0x29, 0x18, 0x4f, 0x01, 0x99, 0x64, 0xe8, 0x77, 0x27, 0x13,
	0xbc, 0x0d, 0xc9, 0xce, 0x88, 0xa9, 0xfc, 0x72, 0xb1, 0xd2, 0x4c, 0xae, 0x37, 0x6e, 0xc0, 0xc6,
	0xc4, 0x26, 0x95, 0xdc, 0x35, 0x58, 0x7b, 0xeb, 0x50, 0x16, 0x85, 0x31, 0xde, 0x43, 0xa1, 0x1a,
	0x10, 0xcc, 0x48, 0xec, 0x2d, 0x85, 0x47, 0x7c, 0x03, 0x39, 0x6b, 0xac, 0x55, 0x47, 0x45, 0x3d,
	0x12, 0xdb, 0xf0, 0x3a, 0xfd, 0xf9, 0xd3, 0x9d, 0xc4, 0x96, 0x66, 0xc6, 0xfd, 0x0d, 0x1f, 0x6e,
	0xce, 0x09, 0xad, 0x4a, 0xe5, 0x2c, 0x4f, 0x49, 0xd0, 0x62, 0xb8, 0x4b, 0x64, 0xfb, 0x65, 0xcc,
	0x2c, 0xd7, 0x34, 0xb9, 0x82, 0xcf, 0x16, 0x49, 0x69, 0xd2, 0x2e, 0x39, 0x1c, 0x84, 0x4a, 0x3a,
	0x20, 0x48, 0x59, 0xbe, 0x1d, 0xd2, 0x82, 0x58, 0x1b, 0x1d, 0x40, 0x27, 0x62, 0x4e, 0x88, 0x01,
	0x11, 0x56, 0x51, 0x84, 0x0c, 0x8f, 0x1b, 0x1b, 0x7f, 0x91, 0xcc, 0x39, 0xcf, 0x77, 0xed, 0x56,
	0x9c, 0x1e, 0x32, 0xbe, 0x6b, 0xcb, 0x01, 0x73, 0x0b, 0xb2, 0x1e, 0x19, 0x29, 0xa3, 0xa2, 0x08,
	0x8f, 0x8c, 0x84, 0x91, 0xe3, 0x3b, 0x71, 0x96, 0xc2, 0xb7, 0x05, 0x1b, 0x95, 0x01, 0xbb, 0xe4,
	0xd5, 0x5a, 0xbc, 0xc3, 0x54, 0x0e, 0xc6, 0x14, 0x39, 0xbd, 0xce, 0x7c, 0xfe, 0x74, 0x27, 0xb5,
	0xa5, 0xf5, 0x97, 0xc6, 0x34, 0xb5, 0x1d, 0x23, 0xa4, 0xc4, 0x94, 0xd3, 0x98, 0x9a, 0x9e, 0xc0,
	0xf5, 0xc9, 0x03, 0x14, 0x9e, 0x82, 0xfe, 0x24, 0xb3, 0x4b, 0x30, 0x43, 0xd1, 0xf8, 0x53, 0x03,
	0xd4, 0x20, 0xec, 0x58, 0x45, 0x08, 0x53, 0xda, 0x84, 0x14, 0x87, 0x61, 0x26, 0x1f, 0xa1, 0x45,
	0xff, 0x9b, 0xe0, 0xcc, 0x98, 0x59, 0xb1, 0xe7, 0x23, 0x58, 0xe5, 0xc0, 0x4d, 0x32, 0x68, 0xcc,
	0x2d, 0xe7, 0xbb, 0x76, 0x78, 0x22, 0x77, 0xe6, 0x40, 0x46, 0xce, 0xa9, 0x69, 0x67, 0x8f, 0x8c,
	0x42, 0x67, 0xe3, 0x25, 0x6c, 0x4c, 0x64, 0xab, 0xea, 0xbb, 0x0b, 0xab, 0xd8, 0x0d, 0x08, 0xb6,
	0xaf, 0x5a, 0x03, 0x4a, 0x6c, 0x55, 0x64, 0x4e, 0xe9, 0x4e, 0x28, 0xb1, 0x8d, 0xdf, 0x92, 0x80,
	0x64, 0xc3, 0x4d, 0x3c, 0x94, 0xa2, 0x9c, 0xe6, 0xd3, 0x75, 0x8a, 0xb9, 0xbe, 0x0d, 0x19, 0x3c,
	0xb0, 0x1d, 0xe2, 0x59, 0x64, 0x16, 0xf3, 0xd0, 0xc2, 0xc1, 0xa0, 0x96, 0xdf, 0xe7, 0xcd, 0x96,
	0x9c, 0x04, 0x43, 0xa8, 0xd1, 0x3b, 0x58, 0x15, 0x8b, 0xd6, 0x10, 0xbb, 0x03, 0x42, 0x0b, 0xa9,
	0xad, 0xe4, 0x4e, 0xae, 0xfc, 0x28, 0xf6, 0x50, 0xa6, 0x72, 0xda, 0x6d, 0x70, 0xf7, 0x53, 0xe1,
	0x5d, 0xf3, 0x58, 0x70, 0x15, 0x07, 0x83, 0x8e, 0x6d, 0xe8, 0x35, 0xa4, 0x6c, 0xcc, 0x70, 0x61,
	0x59, 0x44, 0xdc, 0x5e, 0x10, 0x71, 0x0f, 0x33, 0x3c, 0x1d, 0x4a, 0xec, 0x2d, 0x7e, 0x0b, 0xfa,
	0xf4, 0x71, 0x9c, 0x8f, 0xba, 0xe4, 0x2a, 0xe4, 0xa3, 0x2e, 0xb9, 0xe2, 0xd4, 0x23, 0xb2, 0x0f,
	0x87, 0xa4, 0x10, 0xbe, 0x4e, 0xbc, 0xd4, 0x8a, 0x2f, 0x20, 0x1b, 0x05, 0xff, 0x92, 0x8d, 0xc6,
	0x33, 0xd8, 0x98, 0x48, 0x34, 0x7a, 0xf9, 0x8b, 0x88, 0xeb, 0xe1, 0x3e, 0xc0, 0xc1, 0x59, 0xf3,
	0x78, 0x10, 0xf4, 0x7d, 0xca, 0xbf, 0x5b, 0xf3, 0x95, 0x93, 0xe6, 0x9b, 0xda, 0x61, 0xb3, 0x5e,
	0xad, 0x34, 0xeb, 0x47, 0x87, 0xfa, 0x12, 0xba, 0x0e, 0xba, 0x59, 0x6b, 0x1c, 0x9d, 0x98, 0xd5,
	0x5a, 0xa3, 0x55, 0xa9, 0x56, 0x6b, 0x8d, 0x86, 0xae, 0xa1, 0x3c, 0xc0, 0x69, 0xe5, 0x6d, 0x7d,
	0x4f, 0x7a, 0x25, 0x1e, 0x62, 0xc8, 0x84, 0x3c, 0x8f, 0xb2, 0xb0, 0x2c, 0x6c, 0xfa, 0x12, 0x5a,
	0x83, 0xec, 0xe1, 0x51, 0xb3, 0x25, 0x45, 0x0d, 0xe5, 0x60, 0xa5, 0xf6, 0xee, 0xb8, 0x6e, 0xd6,
	0xf6, 0xf4, 0x04, 0x17, 0xcc, 0xda, 0xe9, 0xd1, 0xf7, 0xb5, 0x3d, 0x3d, 0xc9, 0xe3, 0x71, 0xc7,
	0x46, 0xfd, 0xbb, 0xc3, 0xda, 0x9e, 0x9e, 0x42, 0xeb, 0xb0, 0xc6, 0xe5, 0xda, 0xfe, 0x7e, 0xad,
	0xda, 0xac, 0x9f, 0xd6, 0xf4, 0xe5, 0x87, 0xf7, 0x20, 0x17, 0x1b, 0x94, 0x08, 0x20, 0x2d, 0x29,
	0x5d, 0x5f, 0x42, 0x19, 0x48, 0xf1, 0xc9, 0xa0, 0x6b, 0xe5, 0x3f, 0x12, 0xb0, 0x2e, 0x00, 0x10,
	0x1f, 0x52, 0x0d, 0x12, 0x0c, 0x1d, 0x8b, 0xa0, 0x67, 0x90, 0xe2, 0x5f, 0x18, 0x28, 0x62, 0xd3,
	0xd8, 0xf7, 0x46, 0x71, 0x9e, 0x72, 0x47, 0x7b, 0xa2, 0xa1, 0x57, 0x90, 0x8d, 0xe6, 0x0d, 0x2a,
	0x44, 0x5e, 0x53, 0xb3, 0xab, 0x78, 0x73, 0x8e, 0x45, 0x81, 0xbf, 0x0f, 0xb9, 0xd8, 0x58, 0x40,
	0xc5, 0xd0, 0x73, 0x76, 0xc0, 0x14, 0x6f, 0xcd, 0xb5, 0xa9, 0x38, 0xa7, 0x90, 0xe5, 0xd3, 0x56,
	0x46, 0xf9, 0x4f, 0xe8, 0x39, 0x39, 0xc2, 0x8b, 0xff, 0x9d, 0xd1, 0x2b, 0x96, 0x2c, 0xfc, 0xfa,
	0xf1, 0x9f, 0xdf, 0x13, 0x08, 0xe9, 0xa5, 0xce, 0x88, 0x95, 0x7a, 0x98, 0x59, 0x97, 0xa5, 0x9f,
	0x3b, 0xcc, 0xf9, 0xa5, 0xfc, 0x77, 0x02, 0x6e, 0xc4, 0xf8, 0xcd, 0xf1, 0xbd, 0x10, 0xb1, 0x77,
	0xb0, 0x3e, 0x33, 0x4d, 0xd0, 0xd6, 0xe4, 0x8b, 0x98, 0x9d, 0x61, 0xc5, 0xbb, 0x0b, 0x3c, 0xc6,
	0x98, 0xc4, 0xa8, 0x7c, 0x8c, 0xc9, 0xec, 0x2c, 0x19, 0x63, 0x32, 0x87, 0xfb, 0x51, 0x1d, 0x56,
	0xe3, 0xd4, 0x8c, 0x22, 0xe7, 0x39, 0x13, 0xa1, 0xb8, 0x39, 0xdf, 0x38, 0x4e, 0x29, 0x46, 0x82,
	0xe3, 0x94, 0x66, 0x79, 0x7c, 0x9c, 0xd2, 0x1c, 0xd6, 0x3c, 0x4f, 0x8b, 0x5f, 0xc7, 0xa7, 0xff,
	0x06, 0x00, 0x00, 0xff, 0xff, 0x9c, 0xde, 0x82, 0xf8, 0xa6, 0x0e, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// TokenStoreServiceClient is the client API for TokenStoreService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TokenStoreServiceClient interface {
	Sync(ctx context.Context, opts ...grpc.CallOption) (TokenStoreService_SyncClient, error)
	SaveToken(ctx context.Context, in *SaveTokenRequest, opts ...grpc.CallOption) (*SaveTokenResponse, error)
	RevokeToken(ctx context.Context, in *RevokeTokenRequest, opts ...grpc.CallOption) (*RevokeTokenResponse, error)
	FindToken(ctx context.Context, in *FindJWTRequest, opts ...grpc.CallOption) (*FindJWTResponse, error)
}

type tokenStoreServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTokenStoreServiceClient(cc grpc.ClientConnInterface) TokenStoreServiceClient {
	return &tokenStoreServiceClient{cc}
}

func (c *tokenStoreServiceClient) Sync(ctx context.Context, opts ...grpc.CallOption) (TokenStoreService_SyncClient, error) {
	stream, err := c.cc.NewStream(ctx, &_TokenStoreService_serviceDesc.Streams[0], "/authpb.TokenStoreService/Sync", opts...)
	if err != nil {
		return nil, err
	}
	x := &tokenStoreServiceSyncClient{stream}
	return x, nil
}

type TokenStoreService_SyncClient interface {
	Send(*SyncMessage) error
	Recv() (*SyncMessage, error)
	grpc.ClientStream
}

type tokenStoreServiceSyncClient struct {
	grpc.ClientStream
}

func (x *tokenStoreServiceSyncClient) Send(m *SyncMessage) error {
	return x.ClientStream.SendMsg(m)
}

func (x *tokenStoreServiceSyncClient) Recv() (*SyncMessage, error) {
	m := new(SyncMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *tokenStoreServiceClient) SaveToken(ctx context.Context, in *SaveTokenRequest, opts ...grpc.CallOption) (*SaveTokenResponse, error) {
	out := new(SaveTokenResponse)
	err := c.cc.Invoke(ctx, "/authpb.TokenStoreService/SaveToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tokenStoreServiceClient) RevokeToken(ctx context.Context, in *RevokeTokenRequest, opts ...grpc.CallOption) (*RevokeTokenResponse, error) {
	out := new(RevokeTokenResponse)
	err := c.cc.Invoke(ctx, "/authpb.TokenStoreService/RevokeToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tokenStoreServiceClient) FindToken(ctx context.Context, in *FindJWTRequest, opts ...grpc.CallOption) (*FindJWTResponse, error) {
	out := new(FindJWTResponse)
	err := c.cc.Invoke(ctx, "/authpb.TokenStoreService/FindToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TokenStoreServiceServer is the server API for TokenStoreService service.
type TokenStoreServiceServer interface {
	Sync(TokenStoreService_SyncServer) error
	SaveToken(context.Context, *SaveTokenRequest) (*SaveTokenResponse, error)
	RevokeToken(context.Context, *RevokeTokenRequest) (*RevokeTokenResponse, error)
	FindToken(context.Context, *FindJWTRequest) (*FindJWTResponse, error)
}

// UnimplementedTokenStoreServiceServer can be embedded to have forward compatible implementations.
type UnimplementedTokenStoreServiceServer struct {
}

func (*UnimplementedTokenStoreServiceServer) Sync(srv TokenStoreService_SyncServer) error {
	return status.Errorf(codes.Unimplemented, "method Sync not implemented")
}
func (*UnimplementedTokenStoreServiceServer) SaveToken(ctx context.Context, req *SaveTokenRequest) (*SaveTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveToken not implemented")
}
func (*UnimplementedTokenStoreServiceServer) RevokeToken(ctx context.Context, req *RevokeTokenRequest) (*RevokeTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RevokeToken not implemented")
}
func (*UnimplementedTokenStoreServiceServer) FindToken(ctx context.Context, req *FindJWTRequest) (*FindJWTResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindToken not implemented")
}

func RegisterTokenStoreServiceServer(s *grpc.Server, srv TokenStoreServiceServer) {
	s.RegisterService(&_TokenStoreService_serviceDesc, srv)
}

func _TokenStoreService_Sync_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TokenStoreServiceServer).Sync(&tokenStoreServiceSyncServer{stream})
}

type TokenStoreService_SyncServer interface {
	Send(*SyncMessage) error
	Recv() (*SyncMessage, error)
	grpc.ServerStream
}

type tokenStoreServiceSyncServer struct {
	grpc.ServerStream
}

func (x *tokenStoreServiceSyncServer) Send(m *SyncMessage) error {
	return x.ServerStream.SendMsg(m)
}

func (x *tokenStoreServiceSyncServer) Recv() (*SyncMessage, error) {
	m := new(SyncMessage)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _TokenStoreService_SaveToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TokenStoreServiceServer).SaveToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/authpb.TokenStoreService/SaveToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TokenStoreServiceServer).SaveToken(ctx, req.(*SaveTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TokenStoreService_RevokeToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TokenStoreServiceServer).RevokeToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/authpb.TokenStoreService/RevokeToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TokenStoreServiceServer).RevokeToken(ctx, req.(*RevokeTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TokenStoreService_FindToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindJWTRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TokenStoreServiceServer).FindToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/authpb.TokenStoreService/FindToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TokenStoreServiceServer).FindToken(ctx, req.(*FindJWTRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TokenStoreService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "authpb.TokenStoreService",
	HandlerType: (*TokenStoreServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SaveToken",
			Handler:    _TokenStoreService_SaveToken_Handler,
		},
		{
			MethodName: "RevokeToken",
			Handler:    _TokenStoreService_RevokeToken_Handler,
		},
		{
			MethodName: "FindToken",
			Handler:    _TokenStoreService_FindToken_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Sync",
			Handler:       _TokenStoreService_Sync_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "auth.proto",
}

// AuthenticationServiceClient is the client API for AuthenticationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthenticationServiceClient interface {
	CreateCredentials(ctx context.Context, in *CreateCredentialsRequest, opts ...grpc.CallOption) (*CreateCredentialsResponse, error)
	UpdateEmail(ctx context.Context, in *UpdateEmailRequest, opts ...grpc.CallOption) (*UpdateEmailResponse, error)
	Authenticate(ctx context.Context, in *AuthenticateRequest, opts ...grpc.CallOption) (*AuthenticateResponse, error)
	SetPassword(ctx context.Context, in *SetPasswordRequest, opts ...grpc.CallOption) (*SetPasswordResponse, error)
}

type authenticationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthenticationServiceClient(cc grpc.ClientConnInterface) AuthenticationServiceClient {
	return &authenticationServiceClient{cc}
}

func (c *authenticationServiceClient) CreateCredentials(ctx context.Context, in *CreateCredentialsRequest, opts ...grpc.CallOption) (*CreateCredentialsResponse, error) {
	out := new(CreateCredentialsResponse)
	err := c.cc.Invoke(ctx, "/authpb.AuthenticationService/CreateCredentials", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authenticationServiceClient) UpdateEmail(ctx context.Context, in *UpdateEmailRequest, opts ...grpc.CallOption) (*UpdateEmailResponse, error) {
	out := new(UpdateEmailResponse)
	err := c.cc.Invoke(ctx, "/authpb.AuthenticationService/UpdateEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authenticationServiceClient) Authenticate(ctx context.Context, in *AuthenticateRequest, opts ...grpc.CallOption) (*AuthenticateResponse, error) {
	out := new(AuthenticateResponse)
	err := c.cc.Invoke(ctx, "/authpb.AuthenticationService/Authenticate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authenticationServiceClient) SetPassword(ctx context.Context, in *SetPasswordRequest, opts ...grpc.CallOption) (*SetPasswordResponse, error) {
	out := new(SetPasswordResponse)
	err := c.cc.Invoke(ctx, "/authpb.AuthenticationService/SetPassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthenticationServiceServer is the server API for AuthenticationService service.
type AuthenticationServiceServer interface {
	CreateCredentials(context.Context, *CreateCredentialsRequest) (*CreateCredentialsResponse, error)
	UpdateEmail(context.Context, *UpdateEmailRequest) (*UpdateEmailResponse, error)
	Authenticate(context.Context, *AuthenticateRequest) (*AuthenticateResponse, error)
	SetPassword(context.Context, *SetPasswordRequest) (*SetPasswordResponse, error)
}

// UnimplementedAuthenticationServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAuthenticationServiceServer struct {
}

func (*UnimplementedAuthenticationServiceServer) CreateCredentials(ctx context.Context, req *CreateCredentialsRequest) (*CreateCredentialsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCredentials not implemented")
}
func (*UnimplementedAuthenticationServiceServer) UpdateEmail(ctx context.Context, req *UpdateEmailRequest) (*UpdateEmailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateEmail not implemented")
}
func (*UnimplementedAuthenticationServiceServer) Authenticate(ctx context.Context, req *AuthenticateRequest) (*AuthenticateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Authenticate not implemented")
}
func (*UnimplementedAuthenticationServiceServer) SetPassword(ctx context.Context, req *SetPasswordRequest) (*SetPasswordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetPassword not implemented")
}

func RegisterAuthenticationServiceServer(s *grpc.Server, srv AuthenticationServiceServer) {
	s.RegisterService(&_AuthenticationService_serviceDesc, srv)
}

func _AuthenticationService_CreateCredentials_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCredentialsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthenticationServiceServer).CreateCredentials(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/authpb.AuthenticationService/CreateCredentials",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthenticationServiceServer).CreateCredentials(ctx, req.(*CreateCredentialsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthenticationService_UpdateEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthenticationServiceServer).UpdateEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/authpb.AuthenticationService/UpdateEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthenticationServiceServer).UpdateEmail(ctx, req.(*UpdateEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthenticationService_Authenticate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthenticateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthenticationServiceServer).Authenticate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/authpb.AuthenticationService/Authenticate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthenticationServiceServer).Authenticate(ctx, req.(*AuthenticateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthenticationService_SetPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetPasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthenticationServiceServer).SetPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/authpb.AuthenticationService/SetPassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthenticationServiceServer).SetPassword(ctx, req.(*SetPasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AuthenticationService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "authpb.AuthenticationService",
	HandlerType: (*AuthenticationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCredentials",
			Handler:    _AuthenticationService_CreateCredentials_Handler,
		},
		{
			MethodName: "UpdateEmail",
			Handler:    _AuthenticationService_UpdateEmail_Handler,
		},
		{
			MethodName: "Authenticate",
			Handler:    _AuthenticationService_Authenticate_Handler,
		},
		{
			MethodName: "SetPassword",
			Handler:    _AuthenticationService_SetPassword_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth.proto",
}
