// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auth.proto

package authpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/mwitkow/go-proto-validators"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type JWTPurpose int32

const (
	JWTPurpose_AUTHENTICATION   JWTPurpose = 0
	JWTPurpose_RESOURCES_ACCESS JWTPurpose = 1
	JWTPurpose_VALIDATION       JWTPurpose = 2
)

var JWTPurpose_name = map[int32]string{
	0: "AUTHENTICATION",
	1: "RESOURCES_ACCESS",
	2: "VALIDATION",
}

var JWTPurpose_value = map[string]int32{
	"AUTHENTICATION":   0,
	"RESOURCES_ACCESS": 1,
	"VALIDATION":       2,
}

func (x JWTPurpose) String() string {
	return proto.EnumName(JWTPurpose_name, int32(x))
}

func (JWTPurpose) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{0}
}

type JWTState int32

const (
	JWTState_VALID         JWTState = 0
	JWTState_NOT_VALID     JWTState = 1
	JWTState_EXPIRED       JWTState = 2
	JWTState_REVOKED       JWTState = 3
	JWTState_NOT_SIGNED    JWTState = 4
	JWTState_NOT_EFFECTIVE JWTState = 5
)

var JWTState_name = map[int32]string{
	0: "VALID",
	1: "NOT_VALID",
	2: "EXPIRED",
	3: "REVOKED",
	4: "NOT_SIGNED",
	5: "NOT_EFFECTIVE",
}

var JWTState_value = map[string]int32{
	"VALID":         0,
	"NOT_VALID":     1,
	"EXPIRED":       2,
	"REVOKED":       3,
	"NOT_SIGNED":    4,
	"NOT_EFFECTIVE": 5,
}

func (x JWTState) String() string {
	return proto.EnumName(JWTState_name, int32(x))
}

func (JWTState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{1}
}

type EventAction int32

const (
	EventAction_Delete EventAction = 0
	EventAction_Save   EventAction = 1
)

var EventAction_name = map[int32]string{
	0: "Delete",
	1: "Save",
}

var EventAction_value = map[string]int32{
	"Delete": 0,
	"Save":   1,
}

func (x EventAction) String() string {
	return proto.EnumName(EventAction_name, int32(x))
}

func (EventAction) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{2}
}

type JWTHeader struct {
	Typ                  string   `protobuf:"bytes,1,opt,name=typ,proto3" json:"typ,omitempty"`
	Alg                  string   `protobuf:"bytes,2,opt,name=alg,proto3" json:"alg,omitempty"`
	Kid                  string   `protobuf:"bytes,3,opt,name=kid,proto3" json:"kid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JWTHeader) Reset()         { *m = JWTHeader{} }
func (m *JWTHeader) String() string { return proto.CompactTextString(m) }
func (*JWTHeader) ProtoMessage()    {}
func (*JWTHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{0}
}

func (m *JWTHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JWTHeader.Unmarshal(m, b)
}
func (m *JWTHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JWTHeader.Marshal(b, m, deterministic)
}
func (m *JWTHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JWTHeader.Merge(m, src)
}
func (m *JWTHeader) XXX_Size() int {
	return xxx_messageInfo_JWTHeader.Size(m)
}
func (m *JWTHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_JWTHeader.DiscardUnknown(m)
}

var xxx_messageInfo_JWTHeader proto.InternalMessageInfo

func (m *JWTHeader) GetTyp() string {
	if m != nil {
		return m.Typ
	}
	return ""
}

func (m *JWTHeader) GetAlg() string {
	if m != nil {
		return m.Alg
	}
	return ""
}

func (m *JWTHeader) GetKid() string {
	if m != nil {
		return m.Kid
	}
	return ""
}

type Profile struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	FamilyName           string   `protobuf:"bytes,2,opt,name=family_name,json=familyName,proto3" json:"family_name,omitempty"`
	GivenName            string   `protobuf:"bytes,3,opt,name=given_name,json=givenName,proto3" json:"given_name,omitempty"`
	MiddleName           string   `protobuf:"bytes,4,opt,name=middle_name,json=middleName,proto3" json:"middle_name,omitempty"`
	Nickname             string   `protobuf:"bytes,5,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Picture              string   `protobuf:"bytes,6,opt,name=picture,proto3" json:"picture,omitempty"`
	UpdatedAt            int64    `protobuf:"varint,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Profile) Reset()         { *m = Profile{} }
func (m *Profile) String() string { return proto.CompactTextString(m) }
func (*Profile) ProtoMessage()    {}
func (*Profile) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{1}
}

func (m *Profile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Profile.Unmarshal(m, b)
}
func (m *Profile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Profile.Marshal(b, m, deterministic)
}
func (m *Profile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Profile.Merge(m, src)
}
func (m *Profile) XXX_Size() int {
	return xxx_messageInfo_Profile.Size(m)
}
func (m *Profile) XXX_DiscardUnknown() {
	xxx_messageInfo_Profile.DiscardUnknown(m)
}

var xxx_messageInfo_Profile proto.InternalMessageInfo

func (m *Profile) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Profile) GetFamilyName() string {
	if m != nil {
		return m.FamilyName
	}
	return ""
}

func (m *Profile) GetGivenName() string {
	if m != nil {
		return m.GivenName
	}
	return ""
}

func (m *Profile) GetMiddleName() string {
	if m != nil {
		return m.MiddleName
	}
	return ""
}

func (m *Profile) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *Profile) GetPicture() string {
	if m != nil {
		return m.Picture
	}
	return ""
}

func (m *Profile) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

type Email struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	EmailVerified        bool     `protobuf:"varint,2,opt,name=email_verified,json=emailVerified,proto3" json:"email_verified,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Email) Reset()         { *m = Email{} }
func (m *Email) String() string { return proto.CompactTextString(m) }
func (*Email) ProtoMessage()    {}
func (*Email) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{2}
}

func (m *Email) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Email.Unmarshal(m, b)
}
func (m *Email) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Email.Marshal(b, m, deterministic)
}
func (m *Email) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Email.Merge(m, src)
}
func (m *Email) XXX_Size() int {
	return xxx_messageInfo_Email.Size(m)
}
func (m *Email) XXX_DiscardUnknown() {
	xxx_messageInfo_Email.DiscardUnknown(m)
}

var xxx_messageInfo_Email proto.InternalMessageInfo

func (m *Email) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Email) GetEmailVerified() bool {
	if m != nil {
		return m.EmailVerified
	}
	return false
}

type Claims struct {
	Iss                  string              `protobuf:"bytes,1,opt,name=iss,proto3" json:"iss,omitempty"`
	Sub                  string              `protobuf:"bytes,2,opt,name=sub,proto3" json:"sub,omitempty"`
	Aud                  string              `protobuf:"bytes,3,opt,name=aud,proto3" json:"aud,omitempty"`
	Exp                  int64               `protobuf:"varint,4,opt,name=exp,proto3" json:"exp,omitempty"`
	Nbf                  int64               `protobuf:"varint,5,opt,name=nbf,proto3" json:"nbf,omitempty"`
	Iat                  int64               `protobuf:"varint,6,opt,name=iat,proto3" json:"iat,omitempty"`
	Jti                  string              `protobuf:"bytes,7,opt,name=jti,proto3" json:"jti,omitempty"`
	TokenIntrospection   *TokenIntrospection `protobuf:"bytes,8,opt,name=token_introspection,json=tokenIntrospection,proto3" json:"token_introspection,omitempty"`
	Scope                string              `protobuf:"bytes,9,opt,name=scope,proto3" json:"scope,omitempty"`
	Name                 string              `protobuf:"bytes,10,opt,name=name,proto3" json:"name,omitempty"`
	Email                string              `protobuf:"bytes,11,opt,name=email,proto3" json:"email,omitempty"`
	EmailVerified        bool                `protobuf:"varint,12,opt,name=email_verified,json=emailVerified,proto3" json:"email_verified,omitempty"`
	KeyUrl               string              `protobuf:"bytes,13,opt,name=key_url,json=keyUrl,proto3" json:"key_url,omitempty"`
	State                *State              `protobuf:"bytes,14,opt,name=state,proto3" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Claims) Reset()         { *m = Claims{} }
func (m *Claims) String() string { return proto.CompactTextString(m) }
func (*Claims) ProtoMessage()    {}
func (*Claims) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{3}
}

func (m *Claims) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Claims.Unmarshal(m, b)
}
func (m *Claims) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Claims.Marshal(b, m, deterministic)
}
func (m *Claims) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Claims.Merge(m, src)
}
func (m *Claims) XXX_Size() int {
	return xxx_messageInfo_Claims.Size(m)
}
func (m *Claims) XXX_DiscardUnknown() {
	xxx_messageInfo_Claims.DiscardUnknown(m)
}

var xxx_messageInfo_Claims proto.InternalMessageInfo

func (m *Claims) GetIss() string {
	if m != nil {
		return m.Iss
	}
	return ""
}

func (m *Claims) GetSub() string {
	if m != nil {
		return m.Sub
	}
	return ""
}

func (m *Claims) GetAud() string {
	if m != nil {
		return m.Aud
	}
	return ""
}

func (m *Claims) GetExp() int64 {
	if m != nil {
		return m.Exp
	}
	return 0
}

func (m *Claims) GetNbf() int64 {
	if m != nil {
		return m.Nbf
	}
	return 0
}

func (m *Claims) GetIat() int64 {
	if m != nil {
		return m.Iat
	}
	return 0
}

func (m *Claims) GetJti() string {
	if m != nil {
		return m.Jti
	}
	return ""
}

func (m *Claims) GetTokenIntrospection() *TokenIntrospection {
	if m != nil {
		return m.TokenIntrospection
	}
	return nil
}

func (m *Claims) GetScope() string {
	if m != nil {
		return m.Scope
	}
	return ""
}

func (m *Claims) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Claims) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Claims) GetEmailVerified() bool {
	if m != nil {
		return m.EmailVerified
	}
	return false
}

func (m *Claims) GetKeyUrl() string {
	if m != nil {
		return m.KeyUrl
	}
	return ""
}

func (m *Claims) GetState() *State {
	if m != nil {
		return m.State
	}
	return nil
}

type State struct {
	Service              string   `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	ApiEndpoint          string   `protobuf:"bytes,2,opt,name=api_endpoint,json=apiEndpoint,proto3" json:"api_endpoint,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *State) Reset()         { *m = State{} }
func (m *State) String() string { return proto.CompactTextString(m) }
func (*State) ProtoMessage()    {}
func (*State) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{4}
}

func (m *State) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_State.Unmarshal(m, b)
}
func (m *State) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_State.Marshal(b, m, deterministic)
}
func (m *State) XXX_Merge(src proto.Message) {
	xxx_messageInfo_State.Merge(m, src)
}
func (m *State) XXX_Size() int {
	return xxx_messageInfo_State.Size(m)
}
func (m *State) XXX_DiscardUnknown() {
	xxx_messageInfo_State.DiscardUnknown(m)
}

var xxx_messageInfo_State proto.InternalMessageInfo

func (m *State) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *State) GetApiEndpoint() string {
	if m != nil {
		return m.ApiEndpoint
	}
	return ""
}

type JWT struct {
	Header               *JWTHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Claims               *Claims    `protobuf:"bytes,2,opt,name=claims,proto3" json:"claims,omitempty"`
	Signature            string     `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *JWT) Reset()         { *m = JWT{} }
func (m *JWT) String() string { return proto.CompactTextString(m) }
func (*JWT) ProtoMessage()    {}
func (*JWT) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{5}
}

func (m *JWT) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JWT.Unmarshal(m, b)
}
func (m *JWT) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JWT.Marshal(b, m, deterministic)
}
func (m *JWT) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JWT.Merge(m, src)
}
func (m *JWT) XXX_Size() int {
	return xxx_messageInfo_JWT.Size(m)
}
func (m *JWT) XXX_DiscardUnknown() {
	xxx_messageInfo_JWT.DiscardUnknown(m)
}

var xxx_messageInfo_JWT proto.InternalMessageInfo

func (m *JWT) GetHeader() *JWTHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *JWT) GetClaims() *Claims {
	if m != nil {
		return m.Claims
	}
	return nil
}

func (m *JWT) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

type TokenIntrospection struct {
	Active               bool     `protobuf:"varint,1,opt,name=active,proto3" json:"active,omitempty"`
	Iss                  string   `protobuf:"bytes,2,opt,name=iss,proto3" json:"iss,omitempty"`
	Aud                  string   `protobuf:"bytes,3,opt,name=aud,proto3" json:"aud,omitempty"`
	Iat                  int64    `protobuf:"varint,4,opt,name=iat,proto3" json:"iat,omitempty"`
	Exp                  int64    `protobuf:"varint,5,opt,name=exp,proto3" json:"exp,omitempty"`
	ClientId             string   `protobuf:"bytes,6,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Scope                string   `protobuf:"bytes,7,opt,name=scope,proto3" json:"scope,omitempty"`
	Sub                  string   `protobuf:"bytes,8,opt,name=sub,proto3" json:"sub,omitempty"`
	Jti                  string   `protobuf:"bytes,9,opt,name=jti,proto3" json:"jti,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TokenIntrospection) Reset()         { *m = TokenIntrospection{} }
func (m *TokenIntrospection) String() string { return proto.CompactTextString(m) }
func (*TokenIntrospection) ProtoMessage()    {}
func (*TokenIntrospection) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{6}
}

func (m *TokenIntrospection) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenIntrospection.Unmarshal(m, b)
}
func (m *TokenIntrospection) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenIntrospection.Marshal(b, m, deterministic)
}
func (m *TokenIntrospection) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenIntrospection.Merge(m, src)
}
func (m *TokenIntrospection) XXX_Size() int {
	return xxx_messageInfo_TokenIntrospection.Size(m)
}
func (m *TokenIntrospection) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenIntrospection.DiscardUnknown(m)
}

var xxx_messageInfo_TokenIntrospection proto.InternalMessageInfo

func (m *TokenIntrospection) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

func (m *TokenIntrospection) GetIss() string {
	if m != nil {
		return m.Iss
	}
	return ""
}

func (m *TokenIntrospection) GetAud() string {
	if m != nil {
		return m.Aud
	}
	return ""
}

func (m *TokenIntrospection) GetIat() int64 {
	if m != nil {
		return m.Iat
	}
	return 0
}

func (m *TokenIntrospection) GetExp() int64 {
	if m != nil {
		return m.Exp
	}
	return 0
}

func (m *TokenIntrospection) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *TokenIntrospection) GetScope() string {
	if m != nil {
		return m.Scope
	}
	return ""
}

func (m *TokenIntrospection) GetSub() string {
	if m != nil {
		return m.Sub
	}
	return ""
}

func (m *TokenIntrospection) GetJti() string {
	if m != nil {
		return m.Jti
	}
	return ""
}

type Credentials struct {
	Subject              string   `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Credentials) Reset()         { *m = Credentials{} }
func (m *Credentials) String() string { return proto.CompactTextString(m) }
func (*Credentials) ProtoMessage()    {}
func (*Credentials) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{7}
}

func (m *Credentials) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Credentials.Unmarshal(m, b)
}
func (m *Credentials) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Credentials.Marshal(b, m, deterministic)
}
func (m *Credentials) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Credentials.Merge(m, src)
}
func (m *Credentials) XXX_Size() int {
	return xxx_messageInfo_Credentials.Size(m)
}
func (m *Credentials) XXX_DiscardUnknown() {
	xxx_messageInfo_Credentials.DiscardUnknown(m)
}

var xxx_messageInfo_Credentials proto.InternalMessageInfo

func (m *Credentials) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *Credentials) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Credentials) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type SyncMessage struct {
	Action               EventAction `protobuf:"varint,1,opt,name=action,proto3,enum=authpb.EventAction" json:"action,omitempty"`
	Jti                  string      `protobuf:"bytes,2,opt,name=jti,proto3" json:"jti,omitempty"`
	Info                 *JwtInfo    `protobuf:"bytes,3,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *SyncMessage) Reset()         { *m = SyncMessage{} }
func (m *SyncMessage) String() string { return proto.CompactTextString(m) }
func (*SyncMessage) ProtoMessage()    {}
func (*SyncMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{8}
}

func (m *SyncMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncMessage.Unmarshal(m, b)
}
func (m *SyncMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncMessage.Marshal(b, m, deterministic)
}
func (m *SyncMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncMessage.Merge(m, src)
}
func (m *SyncMessage) XXX_Size() int {
	return xxx_messageInfo_SyncMessage.Size(m)
}
func (m *SyncMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncMessage.DiscardUnknown(m)
}

var xxx_messageInfo_SyncMessage proto.InternalMessageInfo

func (m *SyncMessage) GetAction() EventAction {
	if m != nil {
		return m.Action
	}
	return EventAction_Delete
}

func (m *SyncMessage) GetJti() string {
	if m != nil {
		return m.Jti
	}
	return ""
}

func (m *SyncMessage) GetInfo() *JwtInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

type JwtInfo struct {
	Iss                  string   `protobuf:"bytes,1,opt,name=iss,proto3" json:"iss,omitempty"`
	Aud                  string   `protobuf:"bytes,2,opt,name=aud,proto3" json:"aud,omitempty"`
	Jti                  string   `protobuf:"bytes,3,opt,name=jti,proto3" json:"jti,omitempty"`
	Nbf                  int64    `protobuf:"varint,4,opt,name=nbf,proto3" json:"nbf,omitempty"`
	Exp                  int64    `protobuf:"varint,5,opt,name=exp,proto3" json:"exp,omitempty"`
	State                JWTState `protobuf:"varint,6,opt,name=state,proto3,enum=authpb.JWTState" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JwtInfo) Reset()         { *m = JwtInfo{} }
func (m *JwtInfo) String() string { return proto.CompactTextString(m) }
func (*JwtInfo) ProtoMessage()    {}
func (*JwtInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{9}
}

func (m *JwtInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JwtInfo.Unmarshal(m, b)
}
func (m *JwtInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JwtInfo.Marshal(b, m, deterministic)
}
func (m *JwtInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JwtInfo.Merge(m, src)
}
func (m *JwtInfo) XXX_Size() int {
	return xxx_messageInfo_JwtInfo.Size(m)
}
func (m *JwtInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_JwtInfo.DiscardUnknown(m)
}

var xxx_messageInfo_JwtInfo proto.InternalMessageInfo

func (m *JwtInfo) GetIss() string {
	if m != nil {
		return m.Iss
	}
	return ""
}

func (m *JwtInfo) GetAud() string {
	if m != nil {
		return m.Aud
	}
	return ""
}

func (m *JwtInfo) GetJti() string {
	if m != nil {
		return m.Jti
	}
	return ""
}

func (m *JwtInfo) GetNbf() int64 {
	if m != nil {
		return m.Nbf
	}
	return 0
}

func (m *JwtInfo) GetExp() int64 {
	if m != nil {
		return m.Exp
	}
	return 0
}

func (m *JwtInfo) GetState() JWTState {
	if m != nil {
		return m.State
	}
	return JWTState_VALID
}

type GetJwtInfoRequest struct {
	Jti                  string   `protobuf:"bytes,1,opt,name=jti,proto3" json:"jti,omitempty"`
	Signature            string   `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetJwtInfoRequest) Reset()         { *m = GetJwtInfoRequest{} }
func (m *GetJwtInfoRequest) String() string { return proto.CompactTextString(m) }
func (*GetJwtInfoRequest) ProtoMessage()    {}
func (*GetJwtInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{10}
}

func (m *GetJwtInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetJwtInfoRequest.Unmarshal(m, b)
}
func (m *GetJwtInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetJwtInfoRequest.Marshal(b, m, deterministic)
}
func (m *GetJwtInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetJwtInfoRequest.Merge(m, src)
}
func (m *GetJwtInfoRequest) XXX_Size() int {
	return xxx_messageInfo_GetJwtInfoRequest.Size(m)
}
func (m *GetJwtInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetJwtInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetJwtInfoRequest proto.InternalMessageInfo

func (m *GetJwtInfoRequest) GetJti() string {
	if m != nil {
		return m.Jti
	}
	return ""
}

func (m *GetJwtInfoRequest) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

type GetJwtInfoResponse struct {
	State                JWTState `protobuf:"varint,1,opt,name=state,proto3,enum=authpb.JWTState" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetJwtInfoResponse) Reset()         { *m = GetJwtInfoResponse{} }
func (m *GetJwtInfoResponse) String() string { return proto.CompactTextString(m) }
func (*GetJwtInfoResponse) ProtoMessage()    {}
func (*GetJwtInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{11}
}

func (m *GetJwtInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetJwtInfoResponse.Unmarshal(m, b)
}
func (m *GetJwtInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetJwtInfoResponse.Marshal(b, m, deterministic)
}
func (m *GetJwtInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetJwtInfoResponse.Merge(m, src)
}
func (m *GetJwtInfoResponse) XXX_Size() int {
	return xxx_messageInfo_GetJwtInfoResponse.Size(m)
}
func (m *GetJwtInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetJwtInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetJwtInfoResponse proto.InternalMessageInfo

func (m *GetJwtInfoResponse) GetState() JWTState {
	if m != nil {
		return m.State
	}
	return JWTState_VALID
}

type SaveJwtRequest struct {
	Info                 *JwtInfo `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SaveJwtRequest) Reset()         { *m = SaveJwtRequest{} }
func (m *SaveJwtRequest) String() string { return proto.CompactTextString(m) }
func (*SaveJwtRequest) ProtoMessage()    {}
func (*SaveJwtRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{12}
}

func (m *SaveJwtRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveJwtRequest.Unmarshal(m, b)
}
func (m *SaveJwtRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveJwtRequest.Marshal(b, m, deterministic)
}
func (m *SaveJwtRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveJwtRequest.Merge(m, src)
}
func (m *SaveJwtRequest) XXX_Size() int {
	return xxx_messageInfo_SaveJwtRequest.Size(m)
}
func (m *SaveJwtRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveJwtRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SaveJwtRequest proto.InternalMessageInfo

func (m *SaveJwtRequest) GetInfo() *JwtInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

type SaveJwtResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SaveJwtResponse) Reset()         { *m = SaveJwtResponse{} }
func (m *SaveJwtResponse) String() string { return proto.CompactTextString(m) }
func (*SaveJwtResponse) ProtoMessage()    {}
func (*SaveJwtResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{13}
}

func (m *SaveJwtResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveJwtResponse.Unmarshal(m, b)
}
func (m *SaveJwtResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveJwtResponse.Marshal(b, m, deterministic)
}
func (m *SaveJwtResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveJwtResponse.Merge(m, src)
}
func (m *SaveJwtResponse) XXX_Size() int {
	return xxx_messageInfo_SaveJwtResponse.Size(m)
}
func (m *SaveJwtResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveJwtResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SaveJwtResponse proto.InternalMessageInfo

type DeleteJwtRequest struct {
	Jti                  string   `protobuf:"bytes,1,opt,name=jti,proto3" json:"jti,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteJwtRequest) Reset()         { *m = DeleteJwtRequest{} }
func (m *DeleteJwtRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteJwtRequest) ProtoMessage()    {}
func (*DeleteJwtRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{14}
}

func (m *DeleteJwtRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteJwtRequest.Unmarshal(m, b)
}
func (m *DeleteJwtRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteJwtRequest.Marshal(b, m, deterministic)
}
func (m *DeleteJwtRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteJwtRequest.Merge(m, src)
}
func (m *DeleteJwtRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteJwtRequest.Size(m)
}
func (m *DeleteJwtRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteJwtRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteJwtRequest proto.InternalMessageInfo

func (m *DeleteJwtRequest) GetJti() string {
	if m != nil {
		return m.Jti
	}
	return ""
}

type DeleteJwtResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteJwtResponse) Reset()         { *m = DeleteJwtResponse{} }
func (m *DeleteJwtResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteJwtResponse) ProtoMessage()    {}
func (*DeleteJwtResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{15}
}

func (m *DeleteJwtResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteJwtResponse.Unmarshal(m, b)
}
func (m *DeleteJwtResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteJwtResponse.Marshal(b, m, deterministic)
}
func (m *DeleteJwtResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteJwtResponse.Merge(m, src)
}
func (m *DeleteJwtResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteJwtResponse.Size(m)
}
func (m *DeleteJwtResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteJwtResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteJwtResponse proto.InternalMessageInfo

type CreateCredentialsRequest struct {
	Credentials          *Credentials `protobuf:"bytes,1,opt,name=credentials,proto3" json:"credentials,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *CreateCredentialsRequest) Reset()         { *m = CreateCredentialsRequest{} }
func (m *CreateCredentialsRequest) String() string { return proto.CompactTextString(m) }
func (*CreateCredentialsRequest) ProtoMessage()    {}
func (*CreateCredentialsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{16}
}

func (m *CreateCredentialsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCredentialsRequest.Unmarshal(m, b)
}
func (m *CreateCredentialsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCredentialsRequest.Marshal(b, m, deterministic)
}
func (m *CreateCredentialsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCredentialsRequest.Merge(m, src)
}
func (m *CreateCredentialsRequest) XXX_Size() int {
	return xxx_messageInfo_CreateCredentialsRequest.Size(m)
}
func (m *CreateCredentialsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCredentialsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCredentialsRequest proto.InternalMessageInfo

func (m *CreateCredentialsRequest) GetCredentials() *Credentials {
	if m != nil {
		return m.Credentials
	}
	return nil
}

type CreateCredentialsResponse struct {
	UserTaken            bool     `protobuf:"varint,1,opt,name=user_taken,json=userTaken,proto3" json:"user_taken,omitempty"`
	EmailTaken           bool     `protobuf:"varint,2,opt,name=email_taken,json=emailTaken,proto3" json:"email_taken,omitempty"`
	Code                 string   `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateCredentialsResponse) Reset()         { *m = CreateCredentialsResponse{} }
func (m *CreateCredentialsResponse) String() string { return proto.CompactTextString(m) }
func (*CreateCredentialsResponse) ProtoMessage()    {}
func (*CreateCredentialsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{17}
}

func (m *CreateCredentialsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCredentialsResponse.Unmarshal(m, b)
}
func (m *CreateCredentialsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCredentialsResponse.Marshal(b, m, deterministic)
}
func (m *CreateCredentialsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCredentialsResponse.Merge(m, src)
}
func (m *CreateCredentialsResponse) XXX_Size() int {
	return xxx_messageInfo_CreateCredentialsResponse.Size(m)
}
func (m *CreateCredentialsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCredentialsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCredentialsResponse proto.InternalMessageInfo

func (m *CreateCredentialsResponse) GetUserTaken() bool {
	if m != nil {
		return m.UserTaken
	}
	return false
}

func (m *CreateCredentialsResponse) GetEmailTaken() bool {
	if m != nil {
		return m.EmailTaken
	}
	return false
}

func (m *CreateCredentialsResponse) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type UpdateEmailRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	OldEmail             string   `protobuf:"bytes,2,opt,name=old_email,json=oldEmail,proto3" json:"old_email,omitempty"`
	NewEmail             string   `protobuf:"bytes,3,opt,name=new_email,json=newEmail,proto3" json:"new_email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateEmailRequest) Reset()         { *m = UpdateEmailRequest{} }
func (m *UpdateEmailRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateEmailRequest) ProtoMessage()    {}
func (*UpdateEmailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{18}
}

func (m *UpdateEmailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateEmailRequest.Unmarshal(m, b)
}
func (m *UpdateEmailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateEmailRequest.Marshal(b, m, deterministic)
}
func (m *UpdateEmailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateEmailRequest.Merge(m, src)
}
func (m *UpdateEmailRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateEmailRequest.Size(m)
}
func (m *UpdateEmailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateEmailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateEmailRequest proto.InternalMessageInfo

func (m *UpdateEmailRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UpdateEmailRequest) GetOldEmail() string {
	if m != nil {
		return m.OldEmail
	}
	return ""
}

func (m *UpdateEmailRequest) GetNewEmail() string {
	if m != nil {
		return m.NewEmail
	}
	return ""
}

type UpdateEmailResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateEmailResponse) Reset()         { *m = UpdateEmailResponse{} }
func (m *UpdateEmailResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateEmailResponse) ProtoMessage()    {}
func (*UpdateEmailResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{19}
}

func (m *UpdateEmailResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateEmailResponse.Unmarshal(m, b)
}
func (m *UpdateEmailResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateEmailResponse.Marshal(b, m, deterministic)
}
func (m *UpdateEmailResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateEmailResponse.Merge(m, src)
}
func (m *UpdateEmailResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateEmailResponse.Size(m)
}
func (m *UpdateEmailResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateEmailResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateEmailResponse proto.InternalMessageInfo

type AuthenticateRequest struct {
	Subject              string   `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthenticateRequest) Reset()         { *m = AuthenticateRequest{} }
func (m *AuthenticateRequest) String() string { return proto.CompactTextString(m) }
func (*AuthenticateRequest) ProtoMessage()    {}
func (*AuthenticateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{20}
}

func (m *AuthenticateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthenticateRequest.Unmarshal(m, b)
}
func (m *AuthenticateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthenticateRequest.Marshal(b, m, deterministic)
}
func (m *AuthenticateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthenticateRequest.Merge(m, src)
}
func (m *AuthenticateRequest) XXX_Size() int {
	return xxx_messageInfo_AuthenticateRequest.Size(m)
}
func (m *AuthenticateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthenticateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthenticateRequest proto.InternalMessageInfo

func (m *AuthenticateRequest) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *AuthenticateRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type AuthenticateResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthenticateResponse) Reset()         { *m = AuthenticateResponse{} }
func (m *AuthenticateResponse) String() string { return proto.CompactTextString(m) }
func (*AuthenticateResponse) ProtoMessage()    {}
func (*AuthenticateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{21}
}

func (m *AuthenticateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthenticateResponse.Unmarshal(m, b)
}
func (m *AuthenticateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthenticateResponse.Marshal(b, m, deterministic)
}
func (m *AuthenticateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthenticateResponse.Merge(m, src)
}
func (m *AuthenticateResponse) XXX_Size() int {
	return xxx_messageInfo_AuthenticateResponse.Size(m)
}
func (m *AuthenticateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthenticateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AuthenticateResponse proto.InternalMessageInfo

func (m *AuthenticateResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type SetPasswordRequest struct {
	User                 string   `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	OldPassword          string   `protobuf:"bytes,3,opt,name=old_password,json=oldPassword,proto3" json:"old_password,omitempty"`
	NewPassword          string   `protobuf:"bytes,4,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetPasswordRequest) Reset()         { *m = SetPasswordRequest{} }
func (m *SetPasswordRequest) String() string { return proto.CompactTextString(m) }
func (*SetPasswordRequest) ProtoMessage()    {}
func (*SetPasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{22}
}

func (m *SetPasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetPasswordRequest.Unmarshal(m, b)
}
func (m *SetPasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetPasswordRequest.Marshal(b, m, deterministic)
}
func (m *SetPasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetPasswordRequest.Merge(m, src)
}
func (m *SetPasswordRequest) XXX_Size() int {
	return xxx_messageInfo_SetPasswordRequest.Size(m)
}
func (m *SetPasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetPasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetPasswordRequest proto.InternalMessageInfo

func (m *SetPasswordRequest) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *SetPasswordRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *SetPasswordRequest) GetOldPassword() string {
	if m != nil {
		return m.OldPassword
	}
	return ""
}

func (m *SetPasswordRequest) GetNewPassword() string {
	if m != nil {
		return m.NewPassword
	}
	return ""
}

type SetPasswordResponse struct {
	AlreadyUsed          bool     `protobuf:"varint,1,opt,name=already_used,json=alreadyUsed,proto3" json:"already_used,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetPasswordResponse) Reset()         { *m = SetPasswordResponse{} }
func (m *SetPasswordResponse) String() string { return proto.CompactTextString(m) }
func (*SetPasswordResponse) ProtoMessage()    {}
func (*SetPasswordResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{23}
}

func (m *SetPasswordResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetPasswordResponse.Unmarshal(m, b)
}
func (m *SetPasswordResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetPasswordResponse.Marshal(b, m, deterministic)
}
func (m *SetPasswordResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetPasswordResponse.Merge(m, src)
}
func (m *SetPasswordResponse) XXX_Size() int {
	return xxx_messageInfo_SetPasswordResponse.Size(m)
}
func (m *SetPasswordResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetPasswordResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetPasswordResponse proto.InternalMessageInfo

func (m *SetPasswordResponse) GetAlreadyUsed() bool {
	if m != nil {
		return m.AlreadyUsed
	}
	return false
}

type CreateTokenRequest struct {
	Sub                  string            `protobuf:"bytes,1,opt,name=sub,proto3" json:"sub,omitempty"`
	Audience             string            `protobuf:"bytes,2,opt,name=audience,proto3" json:"audience,omitempty"`
	Scope                []string          `protobuf:"bytes,3,rep,name=scope,proto3" json:"scope,omitempty"`
	ScopeValues          map[string]string `protobuf:"bytes,4,rep,name=scope_values,json=scopeValues,proto3" json:"scope_values,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Data                 map[string]string `protobuf:"bytes,5,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *CreateTokenRequest) Reset()         { *m = CreateTokenRequest{} }
func (m *CreateTokenRequest) String() string { return proto.CompactTextString(m) }
func (*CreateTokenRequest) ProtoMessage()    {}
func (*CreateTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{24}
}

func (m *CreateTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTokenRequest.Unmarshal(m, b)
}
func (m *CreateTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTokenRequest.Marshal(b, m, deterministic)
}
func (m *CreateTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTokenRequest.Merge(m, src)
}
func (m *CreateTokenRequest) XXX_Size() int {
	return xxx_messageInfo_CreateTokenRequest.Size(m)
}
func (m *CreateTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTokenRequest proto.InternalMessageInfo

func (m *CreateTokenRequest) GetSub() string {
	if m != nil {
		return m.Sub
	}
	return ""
}

func (m *CreateTokenRequest) GetAudience() string {
	if m != nil {
		return m.Audience
	}
	return ""
}

func (m *CreateTokenRequest) GetScope() []string {
	if m != nil {
		return m.Scope
	}
	return nil
}

func (m *CreateTokenRequest) GetScopeValues() map[string]string {
	if m != nil {
		return m.ScopeValues
	}
	return nil
}

func (m *CreateTokenRequest) GetData() map[string]string {
	if m != nil {
		return m.Data
	}
	return nil
}

type CreateTokenResponse struct {
	Jwt                  *JWT     `protobuf:"bytes,1,opt,name=jwt,proto3" json:"jwt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateTokenResponse) Reset()         { *m = CreateTokenResponse{} }
func (m *CreateTokenResponse) String() string { return proto.CompactTextString(m) }
func (*CreateTokenResponse) ProtoMessage()    {}
func (*CreateTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{25}
}

func (m *CreateTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTokenResponse.Unmarshal(m, b)
}
func (m *CreateTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTokenResponse.Marshal(b, m, deterministic)
}
func (m *CreateTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTokenResponse.Merge(m, src)
}
func (m *CreateTokenResponse) XXX_Size() int {
	return xxx_messageInfo_CreateTokenResponse.Size(m)
}
func (m *CreateTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTokenResponse proto.InternalMessageInfo

func (m *CreateTokenResponse) GetJwt() *JWT {
	if m != nil {
		return m.Jwt
	}
	return nil
}

func init() {
	proto.RegisterEnum("authpb.JWTPurpose", JWTPurpose_name, JWTPurpose_value)
	proto.RegisterEnum("authpb.JWTState", JWTState_name, JWTState_value)
	proto.RegisterEnum("authpb.EventAction", EventAction_name, EventAction_value)
	proto.RegisterType((*JWTHeader)(nil), "authpb.JWTHeader")
	proto.RegisterType((*Profile)(nil), "authpb.Profile")
	proto.RegisterType((*Email)(nil), "authpb.Email")
	proto.RegisterType((*Claims)(nil), "authpb.Claims")
	proto.RegisterType((*State)(nil), "authpb.State")
	proto.RegisterType((*JWT)(nil), "authpb.JWT")
	proto.RegisterType((*TokenIntrospection)(nil), "authpb.TokenIntrospection")
	proto.RegisterType((*Credentials)(nil), "authpb.Credentials")
	proto.RegisterType((*SyncMessage)(nil), "authpb.SyncMessage")
	proto.RegisterType((*JwtInfo)(nil), "authpb.JwtInfo")
	proto.RegisterType((*GetJwtInfoRequest)(nil), "authpb.GetJwtInfoRequest")
	proto.RegisterType((*GetJwtInfoResponse)(nil), "authpb.GetJwtInfoResponse")
	proto.RegisterType((*SaveJwtRequest)(nil), "authpb.SaveJwtRequest")
	proto.RegisterType((*SaveJwtResponse)(nil), "authpb.SaveJwtResponse")
	proto.RegisterType((*DeleteJwtRequest)(nil), "authpb.DeleteJwtRequest")
	proto.RegisterType((*DeleteJwtResponse)(nil), "authpb.DeleteJwtResponse")
	proto.RegisterType((*CreateCredentialsRequest)(nil), "authpb.CreateCredentialsRequest")
	proto.RegisterType((*CreateCredentialsResponse)(nil), "authpb.CreateCredentialsResponse")
	proto.RegisterType((*UpdateEmailRequest)(nil), "authpb.UpdateEmailRequest")
	proto.RegisterType((*UpdateEmailResponse)(nil), "authpb.UpdateEmailResponse")
	proto.RegisterType((*AuthenticateRequest)(nil), "authpb.AuthenticateRequest")
	proto.RegisterType((*AuthenticateResponse)(nil), "authpb.AuthenticateResponse")
	proto.RegisterType((*SetPasswordRequest)(nil), "authpb.SetPasswordRequest")
	proto.RegisterType((*SetPasswordResponse)(nil), "authpb.SetPasswordResponse")
	proto.RegisterType((*CreateTokenRequest)(nil), "authpb.CreateTokenRequest")
	proto.RegisterMapType((map[string]string)(nil), "authpb.CreateTokenRequest.DataEntry")
	proto.RegisterMapType((map[string]string)(nil), "authpb.CreateTokenRequest.ScopeValuesEntry")
	proto.RegisterType((*CreateTokenResponse)(nil), "authpb.CreateTokenResponse")
}

func init() { proto.RegisterFile("auth.proto", fileDescriptor_8bbd6f3875b0e874) }

var fileDescriptor_8bbd6f3875b0e874 = []byte{
	// 1623 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x57, 0xdd, 0x8e, 0xdb, 0xc6,
	0x15, 0x36, 0x25, 0xad, 0x7e, 0x0e, 0x77, 0xd7, 0xd2, 0xac, 0x13, 0x2b, 0xb4, 0x5b, 0x2b, 0xb4,
	0x1b, 0x6c, 0x6d, 0x64, 0x15, 0xa8, 0x69, 0x1b, 0x04, 0x6d, 0x51, 0x59, 0x4b, 0x27, 0x72, 0xda,
	0xb5, 0x41, 0x69, 0xd7, 0x0e, 0x50, 0x40, 0x98, 0x25, 0x67, 0xe5, 0x59, 0x71, 0x49, 0x86, 0x1c,
	0x4a, 0x15, 0x8a, 0xde, 0xf4, 0xb6, 0xe8, 0x55, 0x9f, 0xa1, 0x77, 0x7d, 0x93, 0xf6, 0x2e, 0x0f,
	0x10, 0xc0, 0xe8, 0x43, 0xf4, 0xb2, 0x98, 0x1f, 0xfe, 0x49, 0xc2, 0x02, 0xbd, 0x9b, 0xf3, 0xc3,
	0x33, 0xe7, 0x7c, 0xf3, 0x9d, 0x73, 0x24, 0x00, 0x9c, 0xb0, 0x77, 0x27, 0x61, 0x14, 0xb0, 0x00,
	0xd5, 0xf9, 0x39, 0xbc, 0x34, 0x1e, 0xce, 0x83, 0x60, 0xee, 0x91, 0x3e, 0x0e, 0x69, 0x1f, 0xfb,
	0x7e, 0xc0, 0x30, 0xa3, 0x81, 0x1f, 0x4b, 0x2f, 0xe3, 0x17, 0x73, 0xca, 0xde, 0x25, 0x97, 0x27,
	0x4e, 0x70, 0xd3, 0xbf, 0x59, 0x51, 0xb6, 0x08, 0x56, 0xfd, 0x79, 0xf0, 0xa9, 0x30, 0x7e, 0xba,
	0xc4, 0x1e, 0x75, 0x31, 0x0b, 0xa2, 0xb8, 0x9f, 0x1d, 0xe5, 0x77, 0xe6, 0x10, 0x5a, 0x2f, 0xdf,
	0x4c, 0xbf, 0x26, 0xd8, 0x25, 0x11, 0x6a, 0x43, 0x95, 0xad, 0xc3, 0xae, 0xd6, 0xd3, 0x8e, 0x5b,
	0x36, 0x3f, 0x72, 0x0d, 0xf6, 0xe6, 0xdd, 0x8a, 0xd4, 0x60, 0x6f, 0xce, 0x35, 0x0b, 0xea, 0x76,
	0xab, 0x52, 0xb3, 0xa0, 0xae, 0xf9, 0xbd, 0x06, 0x8d, 0xd7, 0x51, 0x70, 0x45, 0x3d, 0x82, 0x10,
	0xd4, 0x7c, 0x7c, 0x43, 0x54, 0x08, 0x71, 0x46, 0x8f, 0x40, 0xbf, 0xc2, 0x37, 0xd4, 0x5b, 0xcf,
	0x84, 0x49, 0xc6, 0x02, 0xa9, 0x3a, 0xe3, 0x0e, 0x3f, 0x02, 0x98, 0xd3, 0x25, 0xf1, 0xa5, 0x5d,
	0x46, 0x6e, 0x09, 0xcd, 0x99, 0xfa, 0xfe, 0x86, 0xba, 0xae, 0x47, 0xa4, 0xbd, 0x26, 0xbf, 0x97,
	0x2a, 0xe1, 0x60, 0x40, 0xd3, 0xa7, 0xce, 0x42, 0x58, 0xf7, 0x84, 0x35, 0x93, 0x51, 0x17, 0x1a,
	0x21, 0x75, 0x58, 0x12, 0x91, 0x6e, 0x5d, 0x98, 0x52, 0x91, 0xdf, 0x9a, 0x84, 0x2e, 0x66, 0xc4,
	0x9d, 0x61, 0xd6, 0x6d, 0xf4, 0xb4, 0xe3, 0xaa, 0xdd, 0x52, 0x9a, 0x21, 0x33, 0x4f, 0x61, 0xcf,
	0xba, 0xc1, 0xd4, 0x43, 0xf7, 0x60, 0x8f, 0xf0, 0x83, 0xaa, 0x49, 0x0a, 0xe8, 0x27, 0x70, 0x28,
	0x0e, 0xb3, 0x25, 0x89, 0xe8, 0x15, 0x25, 0xae, 0xa8, 0xab, 0x69, 0x1f, 0x08, 0xed, 0x85, 0x52,
	0x9a, 0xff, 0xad, 0x40, 0x7d, 0xe4, 0x61, 0x7a, 0x13, 0x73, 0xe0, 0x68, 0x1c, 0xa7, 0xe0, 0xd2,
	0x58, 0x68, 0xe2, 0xe4, 0x32, 0x05, 0x37, 0x4e, 0x2e, 0x05, 0xdc, 0x49, 0x06, 0x2e, 0x4e, 0x5c,
	0xae, 0x21, 0x7f, 0x0c, 0x45, 0xd1, 0x55, 0x9b, 0x1f, 0xb9, 0xc6, 0xbf, 0xbc, 0x12, 0x85, 0x56,
	0x6d, 0x7e, 0x14, 0x91, 0x31, 0x13, 0xf5, 0x55, 0x6d, 0x7e, 0xe4, 0x9a, 0x6b, 0x46, 0x45, 0x51,
	0x2d, 0x9b, 0x1f, 0xd1, 0x37, 0x70, 0xc4, 0x82, 0x05, 0xf1, 0x67, 0xd4, 0x67, 0x51, 0x10, 0x87,
	0xc4, 0xe1, 0xec, 0xe9, 0x36, 0x7b, 0xda, 0xb1, 0x3e, 0x30, 0x4e, 0x24, 0xc7, 0x4e, 0xa6, 0xdc,
	0x65, 0x5c, 0xf4, 0xb0, 0x11, 0xdb, 0xd2, 0x71, 0x48, 0x62, 0x27, 0x08, 0x49, 0xb7, 0x25, 0x21,
	0x11, 0x42, 0xf6, 0xf6, 0x50, 0x78, 0xfb, 0x0c, 0x3c, 0xfd, 0x76, 0xf0, 0xf6, 0x77, 0x80, 0x87,
	0xee, 0x43, 0x63, 0x41, 0xd6, 0xb3, 0x24, 0xf2, 0xba, 0x07, 0xe2, 0xf3, 0xfa, 0x82, 0xac, 0xcf,
	0x23, 0x0f, 0x3d, 0x86, 0xbd, 0x98, 0x61, 0x46, 0xba, 0x87, 0x22, 0xfd, 0x83, 0x34, 0xfd, 0x09,
	0x57, 0xda, 0xd2, 0xc6, 0x1f, 0x50, 0xc8, 0x9c, 0x02, 0x31, 0x89, 0x96, 0xd4, 0x49, 0x69, 0x99,
	0x8a, 0xe8, 0x63, 0xd8, 0xc7, 0x21, 0x9d, 0x11, 0xdf, 0x0d, 0x03, 0xea, 0x33, 0xf5, 0x12, 0x3a,
	0x0e, 0xa9, 0xa5, 0x54, 0xe6, 0x12, 0xaa, 0x2f, 0xdf, 0x4c, 0xd1, 0x4f, 0xa1, 0xfe, 0x4e, 0xf4,
	0x88, 0x08, 0xa1, 0x0f, 0x3a, 0xe9, 0x95, 0x59, 0xf3, 0xd8, 0xca, 0x01, 0x7d, 0x02, 0x75, 0x47,
	0xbc, 0xb8, 0x08, 0xa7, 0x0f, 0x0e, 0x53, 0x57, 0xc9, 0x03, 0x5b, 0x59, 0xd1, 0x43, 0x68, 0xc5,
	0x74, 0xee, 0x63, 0xc1, 0x4d, 0x45, 0xfa, 0x4c, 0x61, 0xfe, 0x4b, 0x03, 0xb4, 0xfd, 0x1a, 0xe8,
	0x43, 0xa8, 0x63, 0x87, 0xd1, 0xa5, 0x2c, 0xa5, 0x69, 0x2b, 0x29, 0x25, 0x57, 0xa5, 0x44, 0xae,
	0x6d, 0x2a, 0x71, 0x9a, 0xd4, 0x4a, 0x34, 0xe1, 0xe4, 0xda, 0xcb, 0xc9, 0xf5, 0x00, 0x5a, 0x8e,
	0x47, 0x89, 0xcf, 0x66, 0xd4, 0x55, 0x0d, 0xd3, 0x94, 0x8a, 0xb1, 0x9b, 0x3f, 0x7b, 0xa3, 0xf8,
	0xec, 0x8a, 0xc5, 0xcd, 0x12, 0x8b, 0x39, 0xfb, 0x5a, 0x19, 0xfb, 0xcc, 0x6f, 0x41, 0x1f, 0x45,
	0xc4, 0x25, 0x3e, 0xa3, 0xd8, 0x8b, 0xc5, 0x8b, 0x24, 0x97, 0xd7, 0xc4, 0x61, 0xd9, 0x8b, 0x48,
	0x31, 0xe7, 0x4b, 0xa5, 0xc8, 0x17, 0x03, 0x9a, 0x21, 0x8e, 0xe3, 0x55, 0x10, 0xa5, 0x05, 0x65,
	0xb2, 0xf9, 0x1d, 0xe8, 0x93, 0xb5, 0xef, 0xfc, 0x9e, 0xc4, 0x31, 0x9e, 0x13, 0xf4, 0x4c, 0x02,
	0x14, 0xf8, 0x22, 0xf2, 0xe1, 0xe0, 0x28, 0x45, 0xdf, 0x5a, 0x12, 0x9f, 0x0d, 0x25, 0xa7, 0x95,
	0x4b, 0x9a, 0x68, 0x25, 0x6f, 0x93, 0xc7, 0x50, 0xa3, 0xfe, 0x55, 0x20, 0x6e, 0xd1, 0x07, 0x77,
	0xb3, 0x57, 0x5e, 0xb1, 0xb1, 0x7f, 0x15, 0xd8, 0xc2, 0x68, 0xfe, 0x55, 0x83, 0x86, 0xd2, 0xec,
	0xee, 0x6a, 0x0e, 0x7c, 0xa5, 0x04, 0x3c, 0xbf, 0xa6, 0x9a, 0x5f, 0xa3, 0x7a, 0xb8, 0x56, 0xea,
	0xe1, 0x8d, 0xa7, 0xf8, 0x24, 0x25, 0x79, 0x5d, 0x14, 0xd2, 0x2e, 0x30, 0xae, 0xc4, 0xf3, 0x11,
	0x74, 0xbe, 0x22, 0x2c, 0xcd, 0x90, 0x7c, 0x97, 0x90, 0x38, 0x1b, 0x00, 0x5a, 0x7e, 0x65, 0x89,
	0x6e, 0x95, 0x4d, 0xba, 0xfd, 0x0a, 0x50, 0x31, 0x48, 0x1c, 0x06, 0x7e, 0x4c, 0xf2, 0x14, 0xb4,
	0xdb, 0x53, 0xf8, 0x39, 0x1c, 0x4e, 0xf0, 0x92, 0xbc, 0x5c, 0xb1, 0xf4, 0xfe, 0x14, 0x47, 0xed,
	0x36, 0x1c, 0x3b, 0x70, 0x37, 0xfb, 0x4c, 0xde, 0x68, 0x3e, 0x81, 0xf6, 0x29, 0xf1, 0x08, 0x2b,
	0xc6, 0xda, 0xaa, 0xc5, 0x3c, 0x82, 0x4e, 0xc1, 0x4b, 0x7d, 0xfa, 0x2d, 0x74, 0x47, 0x11, 0xc1,
	0x8c, 0x14, 0x98, 0x96, 0x86, 0xf8, 0x35, 0xe8, 0x4e, 0xae, 0x55, 0x59, 0x65, 0xd4, 0x28, 0x7c,
	0xf0, 0xbc, 0xfe, 0xfe, 0x87, 0x47, 0x95, 0x9e, 0x66, 0x17, 0xfd, 0xcd, 0x00, 0x3e, 0xda, 0x11,
	0x5a, 0x81, 0xc4, 0xf7, 0x48, 0x4c, 0xa2, 0x19, 0xc3, 0x0b, 0xe2, 0xab, 0xb6, 0x6c, 0x71, 0xcd,
	0x94, 0x2b, 0xf8, 0xf6, 0x92, 0xb3, 0x4e, 0xda, 0xe5, 0x96, 0x00, 0xa1, 0x92, 0x0e, 0x08, 0x6a,
	0x4e, 0xe0, 0xa6, 0x23, 0x40, 0x9c, 0xcd, 0x6b, 0x40, 0xe7, 0x62, 0x13, 0x89, 0x15, 0x94, 0x56,
	0x61, 0x40, 0x93, 0xc7, 0x2d, 0x2c, 0xd8, 0x4c, 0xe6, 0x8d, 0x1b, 0x78, 0xee, 0xac, 0xd8, 0x3c,
	0xcd, 0xc0, 0x73, 0xe5, 0x0a, 0x7b, 0x00, 0x2d, 0x9f, 0xac, 0x94, 0x51, 0x35, 0x90, 0x4f, 0x56,
	0xc2, 0x68, 0x7e, 0x00, 0x47, 0xa5, 0xbb, 0x14, 0x9c, 0x33, 0x38, 0x1a, 0x26, 0xec, 0x1d, 0xaf,
	0xd6, 0xe1, 0x4f, 0xad, 0x72, 0x30, 0x37, 0x5a, 0xf7, 0x79, 0xf3, 0xfd, 0x0f, 0x8f, 0x6a, 0x3d,
	0x2d, 0xbc, 0x93, 0x37, 0xf1, 0x93, 0x42, 0xbb, 0x56, 0x36, 0x9c, 0xf2, 0xc6, 0xfd, 0x0c, 0xee,
	0x95, 0x2f, 0x50, 0x78, 0x8a, 0xe1, 0xe0, 0x38, 0x44, 0x75, 0x55, 0xd3, 0x4e, 0x45, 0xf3, 0x9f,
	0x1a, 0xa0, 0x09, 0x61, 0xaf, 0x55, 0x84, 0x34, 0xa5, 0x87, 0x50, 0xe3, 0x30, 0x6c, 0xe5, 0x23,
	0xb4, 0xe8, 0xc7, 0xa5, 0x89, 0x52, 0x30, 0xab, 0xd9, 0xf2, 0x0c, 0xf6, 0x39, 0x70, 0xe5, 0xf9,
	0x52, 0x70, 0xd3, 0x03, 0xcf, 0x4d, 0x6f, 0xe4, 0xce, 0x1c, 0xc8, 0xcc, 0xb9, 0xb6, 0xe9, 0xec,
	0x93, 0x55, 0xea, 0x6c, 0x7e, 0x01, 0x47, 0xa5, 0x6c, 0x55, 0x7d, 0x7c, 0xe9, 0x78, 0x11, 0xc1,
	0xee, 0x7a, 0x96, 0xc4, 0xc4, 0x55, 0x45, 0xea, 0x4a, 0x77, 0x1e, 0x13, 0xd7, 0xfc, 0x5b, 0x15,
	0x90, 0x24, 0x9c, 0x58, 0x01, 0xf9, 0xfb, 0x8b, 0x49, 0xbb, 0x59, 0xa7, 0x98, 0xb9, 0x4f, 0xa0,
	0x89, 0x13, 0x97, 0x12, 0xdf, 0x21, 0xdb, 0x98, 0xa7, 0x16, 0x0e, 0x86, 0x9c, 0xe0, 0xd5, 0x5e,
	0xb5, 0x0c, 0x86, 0x9c, 0xe5, 0x6f, 0x61, 0x5f, 0x1c, 0x66, 0x4b, 0xec, 0x25, 0x24, 0xee, 0xd6,
	0x7a, 0xd5, 0x63, 0x7d, 0xf0, 0xac, 0xd0, 0x28, 0x1b, 0x39, 0x9d, 0x4c, 0xb8, 0xfb, 0x85, 0xf0,
	0xb6, 0x7c, 0x16, 0xad, 0x8b, 0x60, 0xc4, 0xb9, 0x0d, 0x3d, 0x87, 0x9a, 0x8b, 0x19, 0xee, 0xee,
	0x89, 0x88, 0x4f, 0x6e, 0x89, 0x78, 0x8a, 0x19, 0xde, 0x0c, 0x25, 0xbe, 0x35, 0x7e, 0x03, 0xed,
	0xcd, 0xeb, 0xc4, 0xcf, 0x51, 0xb2, 0x4e, 0x87, 0xc3, 0x82, 0xac, 0xf9, 0x0a, 0x11, 0xd9, 0xa7,
	0x2b, 0x44, 0x08, 0x5f, 0x56, 0xbe, 0xd0, 0x8c, 0x5f, 0x42, 0x2b, 0x0b, 0xfe, 0xff, 0x7c, 0x68,
	0x7e, 0x0e, 0x47, 0xa5, 0x44, 0xb3, 0xce, 0xaf, 0x5e, 0xaf, 0x98, 0x9a, 0x26, 0x7a, 0x61, 0x38,
	0xda, 0x5c, 0xff, 0xf4, 0x05, 0xc0, 0xcb, 0x37, 0xd3, 0xd7, 0x49, 0x14, 0x06, 0x31, 0xff, 0x75,
	0x74, 0x38, 0x3c, 0x9f, 0x7e, 0x6d, 0x9d, 0x4d, 0xc7, 0xa3, 0xe1, 0x74, 0xfc, 0xea, 0xac, 0x7d,
	0x07, 0xdd, 0x83, 0xb6, 0x6d, 0x4d, 0x5e, 0x9d, 0xdb, 0x23, 0x6b, 0x32, 0x1b, 0x8e, 0x46, 0xd6,
	0x64, 0xd2, 0xd6, 0xd0, 0x21, 0xc0, 0xc5, 0xf0, 0x77, 0xe3, 0x53, 0xe9, 0x55, 0x79, 0x8a, 0xa1,
	0x99, 0x0e, 0x5c, 0xd4, 0x82, 0x3d, 0x61, 0x6b, 0xdf, 0x41, 0x07, 0xd0, 0x3a, 0x7b, 0x35, 0x9d,
	0x49, 0x51, 0x43, 0x3a, 0x34, 0xac, 0xb7, 0xaf, 0xc7, 0xb6, 0x75, 0xda, 0xae, 0x70, 0xc1, 0xb6,
	0x2e, 0x5e, 0x7d, 0x63, 0x9d, 0xb6, 0xab, 0x3c, 0x1e, 0x77, 0x9c, 0x8c, 0xbf, 0x3a, 0xb3, 0x4e,
	0xdb, 0x35, 0xd4, 0x81, 0x03, 0x2e, 0x5b, 0x2f, 0x5e, 0x58, 0xa3, 0xe9, 0xf8, 0xc2, 0x6a, 0xef,
	0x3d, 0x7d, 0x0c, 0x7a, 0x61, 0x3f, 0x22, 0x80, 0xba, 0x9c, 0xaf, 0xed, 0x3b, 0xa8, 0x09, 0x35,
	0x3e, 0xa4, 0xdb, 0xda, 0xe0, 0x1f, 0x15, 0xe8, 0x08, 0x00, 0x26, 0x2c, 0x88, 0xc8, 0x44, 0xfd,
	0x86, 0xfa, 0x1c, 0x6a, 0x7c, 0xff, 0xa2, 0x6c, 0x9a, 0x16, 0xb6, 0xb1, 0xb1, 0x4b, 0x79, 0xac,
	0x7d, 0xa6, 0xa1, 0x2f, 0xa1, 0xa1, 0x46, 0x3f, 0xfa, 0x30, 0xf3, 0x29, 0xad, 0x10, 0xe3, 0xfe,
	0x96, 0x5e, 0xc1, 0xfe, 0x5b, 0x68, 0x65, 0xd3, 0x1f, 0x75, 0x53, 0xaf, 0xcd, 0xb5, 0x61, 0x7c,
	0xb4, 0xc3, 0xa2, 0x22, 0xfc, 0x01, 0x20, 0xdf, 0x76, 0x28, 0x73, 0xdc, 0x5a, 0xa3, 0x86, 0xb1,
	0xcb, 0xa4, 0x06, 0xe4, 0xfd, 0xbf, 0x7c, 0xff, 0x9f, 0xbf, 0x57, 0x3a, 0xe8, 0x6e, 0xff, 0x7a,
	0xc5, 0xfa, 0x7f, 0xba, 0x66, 0xf4, 0xcf, 0x7d, 0xbe, 0xd6, 0x06, 0xff, 0xae, 0xc0, 0x07, 0x85,
	0xc9, 0x46, 0x03, 0x3f, 0xc5, 0xea, 0x2d, 0x74, 0xb6, 0xf6, 0x08, 0xea, 0x95, 0x7b, 0x61, 0x7b,
	0x7b, 0x19, 0x1f, 0xdf, 0xe2, 0xa1, 0x2a, 0x7a, 0x01, 0x7a, 0x61, 0x88, 0xa3, 0x2c, 0xef, 0xed,
	0x2d, 0x62, 0x3c, 0xd8, 0x69, 0x53, 0x71, 0xc6, 0xb0, 0x5f, 0x1c, 0xca, 0x28, 0x73, 0xde, 0xb1,
	0x0b, 0x8c, 0x87, 0xbb, 0x8d, 0x79, 0x4a, 0x85, 0xf1, 0x97, 0xa7, 0xb4, 0x3d, 0xc1, 0xf3, 0x94,
	0x76, 0xcc, 0xcb, 0xcb, 0xba, 0xf8, 0xa3, 0xfa, 0xb3, 0xff, 0x05, 0x00, 0x00, 0xff, 0xff, 0x05,
	0xd6, 0x31, 0x0c, 0x14, 0x0f, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// TokenStoreServiceClient is the client API for TokenStoreService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TokenStoreServiceClient interface {
	Sync(ctx context.Context, opts ...grpc.CallOption) (TokenStoreService_SyncClient, error)
	SaveJwt(ctx context.Context, in *SaveJwtRequest, opts ...grpc.CallOption) (*SaveJwtResponse, error)
	DeleteJwt(ctx context.Context, in *DeleteJwtRequest, opts ...grpc.CallOption) (*DeleteJwtResponse, error)
	GetJwtInfo(ctx context.Context, in *GetJwtInfoRequest, opts ...grpc.CallOption) (*GetJwtInfoResponse, error)
}

type tokenStoreServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTokenStoreServiceClient(cc grpc.ClientConnInterface) TokenStoreServiceClient {
	return &tokenStoreServiceClient{cc}
}

func (c *tokenStoreServiceClient) Sync(ctx context.Context, opts ...grpc.CallOption) (TokenStoreService_SyncClient, error) {
	stream, err := c.cc.NewStream(ctx, &_TokenStoreService_serviceDesc.Streams[0], "/authpb.TokenStoreService/Sync", opts...)
	if err != nil {
		return nil, err
	}
	x := &tokenStoreServiceSyncClient{stream}
	return x, nil
}

type TokenStoreService_SyncClient interface {
	Send(*SyncMessage) error
	Recv() (*SyncMessage, error)
	grpc.ClientStream
}

type tokenStoreServiceSyncClient struct {
	grpc.ClientStream
}

func (x *tokenStoreServiceSyncClient) Send(m *SyncMessage) error {
	return x.ClientStream.SendMsg(m)
}

func (x *tokenStoreServiceSyncClient) Recv() (*SyncMessage, error) {
	m := new(SyncMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *tokenStoreServiceClient) SaveJwt(ctx context.Context, in *SaveJwtRequest, opts ...grpc.CallOption) (*SaveJwtResponse, error) {
	out := new(SaveJwtResponse)
	err := c.cc.Invoke(ctx, "/authpb.TokenStoreService/SaveJwt", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tokenStoreServiceClient) DeleteJwt(ctx context.Context, in *DeleteJwtRequest, opts ...grpc.CallOption) (*DeleteJwtResponse, error) {
	out := new(DeleteJwtResponse)
	err := c.cc.Invoke(ctx, "/authpb.TokenStoreService/DeleteJwt", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tokenStoreServiceClient) GetJwtInfo(ctx context.Context, in *GetJwtInfoRequest, opts ...grpc.CallOption) (*GetJwtInfoResponse, error) {
	out := new(GetJwtInfoResponse)
	err := c.cc.Invoke(ctx, "/authpb.TokenStoreService/GetJwtInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TokenStoreServiceServer is the server API for TokenStoreService service.
type TokenStoreServiceServer interface {
	Sync(TokenStoreService_SyncServer) error
	SaveJwt(context.Context, *SaveJwtRequest) (*SaveJwtResponse, error)
	DeleteJwt(context.Context, *DeleteJwtRequest) (*DeleteJwtResponse, error)
	GetJwtInfo(context.Context, *GetJwtInfoRequest) (*GetJwtInfoResponse, error)
}

// UnimplementedTokenStoreServiceServer can be embedded to have forward compatible implementations.
type UnimplementedTokenStoreServiceServer struct {
}

func (*UnimplementedTokenStoreServiceServer) Sync(srv TokenStoreService_SyncServer) error {
	return status.Errorf(codes.Unimplemented, "method Sync not implemented")
}
func (*UnimplementedTokenStoreServiceServer) SaveJwt(ctx context.Context, req *SaveJwtRequest) (*SaveJwtResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveJwt not implemented")
}
func (*UnimplementedTokenStoreServiceServer) DeleteJwt(ctx context.Context, req *DeleteJwtRequest) (*DeleteJwtResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteJwt not implemented")
}
func (*UnimplementedTokenStoreServiceServer) GetJwtInfo(ctx context.Context, req *GetJwtInfoRequest) (*GetJwtInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetJwtInfo not implemented")
}

func RegisterTokenStoreServiceServer(s *grpc.Server, srv TokenStoreServiceServer) {
	s.RegisterService(&_TokenStoreService_serviceDesc, srv)
}

func _TokenStoreService_Sync_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TokenStoreServiceServer).Sync(&tokenStoreServiceSyncServer{stream})
}

type TokenStoreService_SyncServer interface {
	Send(*SyncMessage) error
	Recv() (*SyncMessage, error)
	grpc.ServerStream
}

type tokenStoreServiceSyncServer struct {
	grpc.ServerStream
}

func (x *tokenStoreServiceSyncServer) Send(m *SyncMessage) error {
	return x.ServerStream.SendMsg(m)
}

func (x *tokenStoreServiceSyncServer) Recv() (*SyncMessage, error) {
	m := new(SyncMessage)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _TokenStoreService_SaveJwt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveJwtRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TokenStoreServiceServer).SaveJwt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/authpb.TokenStoreService/SaveJwt",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TokenStoreServiceServer).SaveJwt(ctx, req.(*SaveJwtRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TokenStoreService_DeleteJwt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteJwtRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TokenStoreServiceServer).DeleteJwt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/authpb.TokenStoreService/DeleteJwt",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TokenStoreServiceServer).DeleteJwt(ctx, req.(*DeleteJwtRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TokenStoreService_GetJwtInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetJwtInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TokenStoreServiceServer).GetJwtInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/authpb.TokenStoreService/GetJwtInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TokenStoreServiceServer).GetJwtInfo(ctx, req.(*GetJwtInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TokenStoreService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "authpb.TokenStoreService",
	HandlerType: (*TokenStoreServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SaveJwt",
			Handler:    _TokenStoreService_SaveJwt_Handler,
		},
		{
			MethodName: "DeleteJwt",
			Handler:    _TokenStoreService_DeleteJwt_Handler,
		},
		{
			MethodName: "GetJwtInfo",
			Handler:    _TokenStoreService_GetJwtInfo_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Sync",
			Handler:       _TokenStoreService_Sync_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "auth.proto",
}

// AuthenticationServiceClient is the client API for AuthenticationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthenticationServiceClient interface {
	CreateCredentials(ctx context.Context, in *CreateCredentialsRequest, opts ...grpc.CallOption) (*CreateCredentialsResponse, error)
	UpdateEmail(ctx context.Context, in *UpdateEmailRequest, opts ...grpc.CallOption) (*UpdateEmailResponse, error)
	Authenticate(ctx context.Context, in *AuthenticateRequest, opts ...grpc.CallOption) (*AuthenticateResponse, error)
	SetPassword(ctx context.Context, in *SetPasswordRequest, opts ...grpc.CallOption) (*SetPasswordResponse, error)
}

type authenticationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthenticationServiceClient(cc grpc.ClientConnInterface) AuthenticationServiceClient {
	return &authenticationServiceClient{cc}
}

func (c *authenticationServiceClient) CreateCredentials(ctx context.Context, in *CreateCredentialsRequest, opts ...grpc.CallOption) (*CreateCredentialsResponse, error) {
	out := new(CreateCredentialsResponse)
	err := c.cc.Invoke(ctx, "/authpb.AuthenticationService/CreateCredentials", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authenticationServiceClient) UpdateEmail(ctx context.Context, in *UpdateEmailRequest, opts ...grpc.CallOption) (*UpdateEmailResponse, error) {
	out := new(UpdateEmailResponse)
	err := c.cc.Invoke(ctx, "/authpb.AuthenticationService/UpdateEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authenticationServiceClient) Authenticate(ctx context.Context, in *AuthenticateRequest, opts ...grpc.CallOption) (*AuthenticateResponse, error) {
	out := new(AuthenticateResponse)
	err := c.cc.Invoke(ctx, "/authpb.AuthenticationService/Authenticate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authenticationServiceClient) SetPassword(ctx context.Context, in *SetPasswordRequest, opts ...grpc.CallOption) (*SetPasswordResponse, error) {
	out := new(SetPasswordResponse)
	err := c.cc.Invoke(ctx, "/authpb.AuthenticationService/SetPassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthenticationServiceServer is the server API for AuthenticationService service.
type AuthenticationServiceServer interface {
	CreateCredentials(context.Context, *CreateCredentialsRequest) (*CreateCredentialsResponse, error)
	UpdateEmail(context.Context, *UpdateEmailRequest) (*UpdateEmailResponse, error)
	Authenticate(context.Context, *AuthenticateRequest) (*AuthenticateResponse, error)
	SetPassword(context.Context, *SetPasswordRequest) (*SetPasswordResponse, error)
}

// UnimplementedAuthenticationServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAuthenticationServiceServer struct {
}

func (*UnimplementedAuthenticationServiceServer) CreateCredentials(ctx context.Context, req *CreateCredentialsRequest) (*CreateCredentialsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCredentials not implemented")
}
func (*UnimplementedAuthenticationServiceServer) UpdateEmail(ctx context.Context, req *UpdateEmailRequest) (*UpdateEmailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateEmail not implemented")
}
func (*UnimplementedAuthenticationServiceServer) Authenticate(ctx context.Context, req *AuthenticateRequest) (*AuthenticateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Authenticate not implemented")
}
func (*UnimplementedAuthenticationServiceServer) SetPassword(ctx context.Context, req *SetPasswordRequest) (*SetPasswordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetPassword not implemented")
}

func RegisterAuthenticationServiceServer(s *grpc.Server, srv AuthenticationServiceServer) {
	s.RegisterService(&_AuthenticationService_serviceDesc, srv)
}

func _AuthenticationService_CreateCredentials_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCredentialsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthenticationServiceServer).CreateCredentials(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/authpb.AuthenticationService/CreateCredentials",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthenticationServiceServer).CreateCredentials(ctx, req.(*CreateCredentialsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthenticationService_UpdateEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthenticationServiceServer).UpdateEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/authpb.AuthenticationService/UpdateEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthenticationServiceServer).UpdateEmail(ctx, req.(*UpdateEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthenticationService_Authenticate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthenticateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthenticationServiceServer).Authenticate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/authpb.AuthenticationService/Authenticate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthenticationServiceServer).Authenticate(ctx, req.(*AuthenticateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthenticationService_SetPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetPasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthenticationServiceServer).SetPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/authpb.AuthenticationService/SetPassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthenticationServiceServer).SetPassword(ctx, req.(*SetPasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AuthenticationService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "authpb.AuthenticationService",
	HandlerType: (*AuthenticationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCredentials",
			Handler:    _AuthenticationService_CreateCredentials_Handler,
		},
		{
			MethodName: "UpdateEmail",
			Handler:    _AuthenticationService_UpdateEmail_Handler,
		},
		{
			MethodName: "Authenticate",
			Handler:    _AuthenticationService_Authenticate_Handler,
		},
		{
			MethodName: "SetPassword",
			Handler:    _AuthenticationService_SetPassword_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth.proto",
}
